package playfield

import (
	"fmt"
	"strings"
)

// SceneOpts は生成する静止画カーネルのパラメータ。
type SceneOpts struct {
	LineHeight int // 1 playfield 行あたりの scanline 数（既定 4）
}

// GenerateSymmetricASM は対称(reflect)playfield の静止画 DASM ソースを自己完結で吐く
// （include 不要）。設計は ABB(kirkjerk) の対称カーネルを土台に、水背景の per-row COLUBK を追加。
//
// art[i] は画面 TOP から i 番目の行（左半 20 列、'.'/'X'）。water[i]/lily[i] は NTSC 色バイト。
// 3 スライスは同じ長さ（= 行数）。表示は左半を描き CTRLPF reflect で右半を鏡像生成する。
//
// カーネルのレジスタ設定順は COLUBK→PF0→PF1→PF2→COLUPF。理由:
//   - WSYNC 後、各 PFn を「その描画領域が来る直前」に just-in-time で書く（ABB 同様 glitch 無し）。
//   - COLUBK は行全体に効くので先頭で（水背景を全幅正しく）。COLUPF は最後（lily 色は per-row で
//     変化が疎なため、行替わりの僅かな遅延は許容）。
func GenerateSymmetricASM(art []string, water, lily []byte, opts SceneOpts) (string, error) {
	rows := len(art)
	if rows == 0 {
		return "", fmt.Errorf("art is empty")
	}
	if len(water) != rows || len(lily) != rows {
		return "", fmt.Errorf("water(%d)/lily(%d) length must equal art rows(%d)", len(water), len(lily), rows)
	}
	if rows > 256 {
		return "", fmt.Errorf("rows %d exceeds index range (max 256)", rows)
	}
	h := opts.LineHeight
	if h <= 0 {
		h = 4
	}

	// 各行(TOP→BOTTOM)を検証済みビット順で PF0/PF1/PF2 へ符号化。
	pf0 := make([]byte, rows)
	pf1 := make([]byte, rows)
	pf2 := make([]byte, rows)
	for i, line := range art {
		a, b, c := EncodeSymmetric(ParseASCIIRow(line))
		pf0[i], pf1[i], pf2[i] = a, b, c
	}

	// テーブルは x で引かれ、x は rows-1（TOP）から下る。よって table[rows-1] が画面最上段。
	// table[i] = art 行 (rows-1-i) の値、として「逆順」に出力すれば art[0] が TOP になる。
	emit := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&sb, "        .byte $%02X\n", vals[rows-1-i])
		}
		return sb.String()
	}

	var b strings.Builder
	fmt.Fprintf(&b, `; monet_m1 — generated by cmd/genpf (internal/playfield.GenerateSymmetricASM)
; 対称(reflect) playfield 静止画。行数=%d 行高=%d scanline。左半を描き右半は鏡像。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
PFHGT   = $80          ; 行高カウンタ(RAM)

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #1
        sta CTRLPF      ; reflect（右半=左半の鏡像）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
VBlank: sta WSYNC
        dex
        bne VBlank
        lda #0
        sta VBLANK

        ldx #%d           ; 行インデックス（rows-1, TOP から下る）
        lda #%d
        sta PFHGT
PFLoop:
        sta WSYNC
        lda BGColors,x    ; 水背景（行全体に効くので先頭）
        sta COLUBK
        lda PF0Data,x     ; PF0/1/2 を just-in-time で
        sta PF0
        lda PF1Data,x
        sta PF1
        lda PF2Data,x
        sta PF2
        lda PFColors,x    ; lily 色（最後）
        sta COLUPF
        dec PFHGT
        bne PFSame
        lda #%d
        sta PFHGT
        dex
        bmi PFDone
PFSame:
        jmp PFLoop
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        ldx #30
OScan:  sta WSYNC
        dex
        bne OScan
        jmp NextFrame

`, rows, h, rows-1, h, h)

	b.WriteString(emit("PF0Data", pf0))
	b.WriteString("\n")
	b.WriteString(emit("PF1Data", pf1))
	b.WriteString("\n")
	b.WriteString(emit("PF2Data", pf2))
	b.WriteString("\n")
	b.WriteString(emit("PFColors", lily))
	b.WriteString("\n")
	b.WriteString(emit("BGColors", water))
	b.WriteString("\n")
	b.WriteString("        org $FFFC\n        .word Start\n        .word Start\n")

	return b.String(), nil
}
