package playfield

import (
	"fmt"
	"strings"
)

// SceneOpts は生成するカーネルのパラメータ。
type SceneOpts struct {
	LineHeight int // 1 playfield 行あたりの scanline 数（既定 4）
	Speed      int // アニメ: 1 シフトあたりのフレーム数（小さいほど速い。既定 6）
}

// GenerateSymmetricASM は対称(reflect)playfield の静止画 DASM ソースを自己完結で吐く
// （include 不要）。設計は ABB(kirkjerk) の対称カーネルを土台に、水背景の per-row COLUBK を追加。
//
// art[i] は画面 TOP から i 番目の行（左半 20 列、'.'/'X'）。water[i]/lily[i] は NTSC 色バイト。
// 3 スライスは同じ長さ（= 行数）。表示は左半を描き CTRLPF reflect で右半を鏡像生成する。
//
// カーネルのレジスタ設定順は COLUBK→PF0→PF1→PF2→COLUPF。理由:
//   - WSYNC 後、各 PFn を「その描画領域が来る直前」に just-in-time で書く（ABB 同様 glitch 無し）。
//   - COLUBK は行全体に効くので先頭で（水背景を全幅正しく）。COLUPF は最後（lily 色は per-row で
//     変化が疎なため、行替わりの僅かな遅延は許容）。
func GenerateSymmetricASM(art []string, water, lily []byte, opts SceneOpts) (string, error) {
	rows := len(art)
	if rows == 0 {
		return "", fmt.Errorf("art is empty")
	}
	if len(water) != rows || len(lily) != rows {
		return "", fmt.Errorf("water(%d)/lily(%d) length must equal art rows(%d)", len(water), len(lily), rows)
	}
	if rows > 256 {
		return "", fmt.Errorf("rows %d exceeds index range (max 256)", rows)
	}
	h := opts.LineHeight
	if h <= 0 {
		h = 4
	}

	// 各行(TOP→BOTTOM)を検証済みビット順で PF0/PF1/PF2 へ符号化。
	pf0 := make([]byte, rows)
	pf1 := make([]byte, rows)
	pf2 := make([]byte, rows)
	for i, line := range art {
		a, b, c := EncodeSymmetric(ParseASCIIRow(line))
		pf0[i], pf1[i], pf2[i] = a, b, c
	}

	// テーブルは x で引かれ、x は rows-1（TOP）から下る。よって table[rows-1] が画面最上段。
	// table[i] = art 行 (rows-1-i) の値、として「逆順」に出力すれば art[0] が TOP になる。
	emit := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&sb, "        .byte $%02X\n", vals[rows-1-i])
		}
		return sb.String()
	}

	var b strings.Builder
	fmt.Fprintf(&b, `; monet_m1 — generated by cmd/genpf (internal/playfield.GenerateSymmetricASM)
; 対称(reflect) playfield 静止画。行数=%d 行高=%d scanline。左半を描き右半は鏡像。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
PFHGT   = $80          ; 行高カウンタ(RAM)

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #1
        sta CTRLPF      ; reflect（右半=左半の鏡像）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
VBlank: sta WSYNC
        dex
        bne VBlank
        lda #0
        sta VBLANK

        ldx #%d           ; 行インデックス（rows-1, TOP から下る）
        lda #%d
        sta PFHGT
PFLoop:
        sta WSYNC
        lda BGColors,x    ; 水背景（行全体に効くので先頭）
        sta COLUBK
        lda PF0Data,x     ; PF0/1/2 を just-in-time で
        sta PF0
        lda PF1Data,x
        sta PF1
        lda PF2Data,x
        sta PF2
        lda PFColors,x    ; lily 色（最後）
        sta COLUPF
        dec PFHGT
        bne PFSame
        lda #%d
        sta PFHGT
        dex
        bmi PFDone
PFSame:
        jmp PFLoop
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        ldx #30
OScan:  sta WSYNC
        dex
        bne OScan
        jmp NextFrame

`, rows, h, rows-1, h, h)

	b.WriteString(emit("PF0Data", pf0))
	b.WriteString("\n")
	b.WriteString(emit("PF1Data", pf1))
	b.WriteString("\n")
	b.WriteString(emit("PF2Data", pf2))
	b.WriteString("\n")
	b.WriteString(emit("PFColors", lily))
	b.WriteString("\n")
	b.WriteString(emit("BGColors", water))
	b.WriteString("\n")
	b.WriteString("        org $FFFC\n        .word Start\n        .word Start\n")

	return b.String(), nil
}

// GenerateAsymmetricASM は非対称 playfield の静止画 DASM ソースを自己完結で吐く。
// 左半(col0..19)と右半(col20..39)で別の絵を出す＝有機的・非対称な水面/睡蓮向き。
// 1 ライン内で PF0/1/2 を A(左)→B(右) に詰め替える ABB(kirkjerk) の「repeated」非対称カーネルを
// 逐語転写（cycle 臨界・72サイクル/ライン）。`tay`/`sty` で B 書き換えの間合いを作る。
//
// art[i] は TOP から i 番目の行（40 列、'.'/'X'）。lily[i] は per-row COLUPF。
// water[i] は per-row COLUBK（Monet の横色帯）。lily は frame 固定の COLUPF（前景）。
// 非対称ループは 72 サイクルで余裕が無いため、per-row 化できる色は 1 チャンネルのみ＝面積の
// 大きい水(COLUBK)を per-row に、睡蓮(COLUPF)を定数にする。タイミングは対称版と同じく、ループ
// 先頭のロード先を COLUBK にするだけ（COLUPF は VBLANK で一度だけ設定）。
func GenerateAsymmetricASM(art []string, water []byte, lily byte, opts SceneOpts) (string, error) {
	rows := len(art)
	if rows == 0 {
		return "", fmt.Errorf("art is empty")
	}
	if len(water) != rows {
		return "", fmt.Errorf("water(%d) length must equal art rows(%d)", len(water), rows)
	}
	if rows > 256 {
		return "", fmt.Errorf("rows %d exceeds index range (max 256)", rows)
	}
	h := opts.LineHeight
	if h <= 0 {
		h = 4
	}

	pf0a := make([]byte, rows)
	pf1a := make([]byte, rows)
	pf2a := make([]byte, rows)
	pf0b := make([]byte, rows)
	pf1b := make([]byte, rows)
	pf2b := make([]byte, rows)
	for i, line := range art {
		r := EncodeAsymmetric(ParseASCIIRow(line))
		pf0a[i], pf1a[i], pf2a[i] = r.PF0A, r.PF1A, r.PF2A
		pf0b[i], pf1b[i], pf2b[i] = r.PF0B, r.PF1B, r.PF2B
	}

	emit := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&sb, "        .byte $%02X\n", vals[rows-1-i])
		}
		return sb.String()
	}

	var b strings.Builder
	fmt.Fprintf(&b, `; asym playfield — generated by internal/playfield.GenerateAsymmetricASM
; 非対称(左右独立) playfield 静止画。行数=%d 行高=%d。1ライン内で PF を A→B に詰め替え（ABB転写）。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
PFHGT   = $80

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #0
        sta CTRLPF      ; reflect 無し（非対称はライン内の詰め替えで作る）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
VBlank: sta WSYNC
        dex
        bne VBlank
        lda #$%02X
        sta COLUPF      ; 睡蓮（frame 固定の前景色）
        lda #0
        sta VBLANK

        ldx #%d
        lda #%d
        sta PFHGT
PFLoop:
        sta WSYNC                 ; (0)
        lda BGColors,x            ; (4)
        sta COLUBK                ; (7)  水（per-row、HBLANK 中＝行全体に効く）
        lda PF0DataA,x            ; (11)
        sta PF0                   ; (14)
        lda PF1DataA,x            ; (18)
        sta PF1                   ; (21)
        lda PF2DataA,x            ; (25)
        sta PF2                   ; (28)  左半確定
        lda PF0DataB,x            ; (32)
        tay                       ; (34)  PF0B を Y に退避
        lda PF1DataB,x            ; (38)
        sta PF1                   ; (41)  右半 PF1
        sty PF0                   ; (44)  右半 PF0
        lda PF2DataB,x            ; (48)
        sta PF2                   ; (51)  右半 PF2
        dec PFHGT                 ; (56)
        bne PFSkip                ; (58/59)
        lda #%d                   ; (60)
        sta PFHGT                 ; (63)
        dex                       ; (65)
        cpx #$FF                  ; (67)
        beq PFDone                ; (69)
PFSkip:
        jmp PFLoop                ; (72)
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        ldx #30
OScan:  sta WSYNC
        dex
        bne OScan
        jmp NextFrame

`, rows, h, lily, rows-1, h, h)

	b.WriteString(emit("PF0DataA", pf0a))
	b.WriteString("\n")
	b.WriteString(emit("PF1DataA", pf1a))
	b.WriteString("\n")
	b.WriteString(emit("PF2DataA", pf2a))
	b.WriteString("\n")
	b.WriteString(emit("PF0DataB", pf0b))
	b.WriteString("\n")
	b.WriteString(emit("PF1DataB", pf1b))
	b.WriteString("\n")
	b.WriteString(emit("PF2DataB", pf2b))
	b.WriteString("\n")
	b.WriteString(emit("BGColors", water))
	b.WriteString("\n")
	b.WriteString("        org $FFFC\n        .word Start\n        .word Start\n")

	return b.String(), nil
}

// GenerateMonetSpriteASM は「Monet 水面（per-scanline 色帯）の上を、滑らかに流れる睡蓮スプライト」
// を出す統合カーネル（M3 ステップ2）。水色(COLUBK)とスプライト(GRP0)を各 scanline で 1 バイトずつ
// テーブルから読むだけ＝両方 HBLANK 内に確定し、サイクル予算に余裕。HMOVE で毎フレーム drift。
//
// bg/grp0 はともに長さ192（可視 scanline ごと）。grp0 は睡蓮の縦位置にだけ非ゼロ。
// nusiz/colup0 は NUSIZ0/COLUP0、hmp0 は毎フレーム HMOVE strobe で適用する動き（$F0=右1px）。
func GenerateMonetSpriteASM(bg, grp0 []byte, nusiz, colup0, hmp0 byte) (string, error) {
	if len(bg) != 192 || len(grp0) != 192 {
		return "", fmt.Errorf("bg(%d)/grp0(%d) must both be length 192", len(bg), len(grp0))
	}
	emit := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for _, v := range vals {
			fmt.Fprintf(&sb, "        .byte $%02X\n", v)
		}
		return sb.String()
	}
	var b strings.Builder
	fmt.Fprintf(&b, `; Monet water + flowing lily sprite — internal/playfield.GenerateMonetSpriteASM
; per-scanline COLUBK(水) + per-scanline GRP0(睡蓮) をテーブルから。HMOVE で毎フレーム drift。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUBK  = $09
RESP0   = $10
GRP0    = $1B
HMP0    = $20
HMOVE   = $2A

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #$%02X
        sta COLUP0
        lda #$%02X
        sta NUSIZ0
        sta WSYNC
        ldx #12
DLY:    dex
        bne DLY
        sta RESP0
        lda #$%02X
        sta HMP0

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        sta WSYNC
        sta HMOVE       ; 累積モーション適用（毎フレーム drift）
        ldx #36
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ldy #0
VL:     sta WSYNC
        lda GRP0Tab,y   ; 睡蓮（HBLANK 内）
        sta GRP0
        lda BGTab,y     ; 水（HBLANK 内）
        sta COLUBK
        iny
        cpy #192
        bne VL
        lda #0
        sta GRP0

        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

`, colup0, nusiz, hmp0)
	b.WriteString(emit("GRP0Tab", grp0))
	b.WriteString("\n")
	b.WriteString(emit("BGTab", bg))
	b.WriteString("\n")
	b.WriteString("        org $FFFC\n        .word Start\n        .word Start\n")
	return b.String(), nil
}

// GenerateAsymmetricShimmerASM は非対称 Monet を「水面のきらめき」アニメ化する（M2 ステップ1）。
// 水色テーブルを RAM に置き、毎フレーム VBLANK 中にスクロール位置をずらして詰め直す＝色帯が
// ゆっくり流れる。サイクル臨界の可視ループは静止版と同一（読み先が ROM→RAM になるだけ＝同サイクル）。
// VBLANK/Overscan は TIM64T タイマー方式で、フレーム内の計算量に関係なくライン数を安定させる。
//
// waterCycle は巡回する水色パレット（長さ=行数）。lily は定数 COLUPF。opts.Speed = 1 シフト/N フレーム。
func GenerateAsymmetricShimmerASM(art []string, waterCycle []byte, lily byte, opts SceneOpts) (string, error) {
	rows := len(art)
	if rows == 0 {
		return "", fmt.Errorf("art is empty")
	}
	if len(waterCycle) != rows {
		return "", fmt.Errorf("waterCycle(%d) length must equal art rows(%d)", len(waterCycle), rows)
	}
	if rows > 120 { // RAM 水バッファ($90..)＋2×パレット ROM の都合で控えめに
		return "", fmt.Errorf("rows %d too large for animated kernel (max 120)", rows)
	}
	h := opts.LineHeight
	if h <= 0 {
		h = 4
	}
	speed := opts.Speed
	if speed <= 0 {
		speed = 6
	}

	pf0a := make([]byte, rows)
	pf1a := make([]byte, rows)
	pf2a := make([]byte, rows)
	pf0b := make([]byte, rows)
	pf1b := make([]byte, rows)
	pf2b := make([]byte, rows)
	for i, line := range art {
		r := EncodeAsymmetric(ParseASCIIRow(line))
		pf0a[i], pf1a[i], pf2a[i] = r.PF0A, r.PF1A, r.PF2A
		pf0b[i], pf1b[i], pf2b[i] = r.PF0B, r.PF1B, r.PF2B
	}
	emit := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&sb, "        .byte $%02X\n", vals[rows-1-i])
		}
		return sb.String()
	}
	// BGCycle: 2×行数。BGCycle[k] = 逆順 waterCycle の (k mod rows)。Offset=0 で静止版の並びに一致。
	bg := make([]byte, 2*rows)
	for k := 0; k < 2*rows; k++ {
		bg[k] = waterCycle[rows-1-(k%rows)]
	}
	emitRaw := func(name string, vals []byte) string {
		var sb strings.Builder
		sb.WriteString(name + "\n")
		for _, v := range vals {
			fmt.Fprintf(&sb, "        .byte $%02X\n", v)
		}
		return sb.String()
	}

	var b strings.Builder
	fmt.Fprintf(&b, `; asym Monet shimmer — internal/playfield.GenerateAsymmetricShimmerASM
; 非対称 Monet を水面きらめきアニメ化。RAM 水テーブルを毎フレーム VBLANK でスクロール再充填。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
INTIM   = $0284
TIM64T  = $0296
PFHGT   = $80
Offset  = $81
SubCnt  = $82
WaterRAM = $90

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #0
        sta CTRLPF
        sta Offset
        sta SubCnt
        lda #$%02X
        sta COLUPF      ; 睡蓮（定数 COLUPF）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #44
        sta TIM64T      ; VBLANK タイマー

        ; --- スクロール位置更新（%d フレームに 1 シフト）---
        inc SubCnt
        lda SubCnt
        cmp #%d
        bcc NoShift
        lda #0
        sta SubCnt
        inc Offset
        lda Offset
        cmp #%d
        bcc NoShift
        lda #0
        sta Offset
NoShift:
        ; --- WaterRAM[i] = BGCycle[Offset+i], i=0..rows-1 ---
        ldx #%d
Fill:   txa
        clc
        adc Offset
        tay
        lda BGCycle,y
        sta WaterRAM,x
        dex
        bpl Fill

WaitVB: lda INTIM
        bne WaitVB
        sta WSYNC
        lda #0
        sta VBLANK

        ldx #%d
        lda #%d
        sta PFHGT
PFLoop:
        sta WSYNC                 ; (0)
        lda WaterRAM,x            ; (4)  per-row 水（RAM・アニメ）
        sta COLUBK                ; (7)
        lda PF0DataA,x            ; (11)
        sta PF0                   ; (14)
        lda PF1DataA,x            ; (18)
        sta PF1                   ; (21)
        lda PF2DataA,x            ; (25)
        sta PF2                   ; (28)
        lda PF0DataB,x            ; (32)
        tay                       ; (34)
        lda PF1DataB,x            ; (38)
        sta PF1                   ; (41)
        sty PF0                   ; (44)
        lda PF2DataB,x            ; (48)
        sta PF2                   ; (51)
        dec PFHGT                 ; (56)
        bne PFSkip
        lda #%d
        sta PFHGT
        dex
        cpx #$FF
        beq PFDone
PFSkip:
        jmp PFLoop
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        lda #35
        sta TIM64T      ; Overscan タイマー
WaitOS: lda INTIM
        bne WaitOS
        sta WSYNC
        jmp NextFrame

`, lily, speed, speed, rows, rows-1, rows-1, h, h)

	b.WriteString(emit("PF0DataA", pf0a))
	b.WriteString("\n")
	b.WriteString(emit("PF1DataA", pf1a))
	b.WriteString("\n")
	b.WriteString(emit("PF2DataA", pf2a))
	b.WriteString("\n")
	b.WriteString(emit("PF0DataB", pf0b))
	b.WriteString("\n")
	b.WriteString(emit("PF1DataB", pf1b))
	b.WriteString("\n")
	b.WriteString(emit("PF2DataB", pf2b))
	b.WriteString("\n")
	b.WriteString(emitRaw("BGCycle", bg))
	b.WriteString("\n")
	b.WriteString("        org $FFFC\n        .word Start\n        .word Start\n")

	return b.String(), nil
}
