; litmus_jmpind_pos — indirect-jump object positioning (GENERATED by
;   scripts/gen_litmus_jmpind_pos.py — edit that, not this file)
;
; Claim: `JMP (ptr)` into a table of hardcoded positioning lines places an object
;        at x(k) = x(0) + 15k, with NO cycle-counting delay loop in the kernel.
; Source: Stella list, star fire - return of the starfield ?!?, 2002-07,
;         Erik Mooney 200207/msg00330+00334; Manuel Polik 200207/msg00332.
;
; P0 (COLUP0, GRP0=$80 = one pixel) is the dispatched object.
; BL (COLUPF) is the static control: positioned once, never re-strobed.
; Band order is a permutation, so a band-index artefact cannot pass.
;
; 25 bands x 5 lines = 125 picture lines, 67 blank.
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUPF  = $08
COLUBK  = $09
RESP0   = $10
RESBL   = $14
GRP0    = $1B
ENABL   = $1F
HMP0    = $20
HMOVE   = $2A
HMCLR   = $2B
ptr     = $80
scratch = $82        ; DEC target used purely to burn 5 cycles
band    = $83

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        sta HMCLR
        lda #$00
        sta COLUBK          ; black
        lda #$0E
        sta COLUP0          ; white dot = the dispatched object
        lda #$46
        sta COLUPF          ; red bar = the static control
        lda #$80
        sta GRP0            ; one pixel, leftmost bit
        lda #0
        sta NUSIZ0
        lda #$02
        sta ENABL           ; ball on, 1 clock wide (CTRLPF=0)

NextFrame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #2
        sta VBLANK
        ; --- the static control: RESBL once per frame at a fixed cycle, far right
        sta WSYNC
        ldx #12
Bd:     dex
        bne Bd              ; 2 + 5*11 + 4 = 61 cy
        sta RESBL
        sta HMCLR
        ldx #36
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ; ================= bands =================
        ldx #0
        stx band
Band:
        ; --- setup line: load the dispatch pointer and the fine nibble
        sta WSYNC
        ldx band
        lda TabLo,x
        sta ptr
        lda TabHi,x
        sta ptr+1
        lda TabFine,x
        sta HMP0
        ; --- positioning line: base delay, then the indirect dispatch
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        jmp (ptr)           ; 5 cy -> one of Pos0..Pos8
        ; unreachable by construction; a poison here would never execute

AfterPos:
        sta WSYNC
        sta HMOVE           ; apply the fine nibble (0 for the coarse bands)
        sta WSYNC           ; draw line 1  <- graded
        sta WSYNC           ; draw line 2  <- graded
        sta HMCLR
        inc band
        lda band
        cmp #25
        bne Band

        ; --- remaining picture lines, nothing moves
        ldx #67
Fill:   sta WSYNC
        dex
        bne Fill

        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

; ---- the unrolled positioning lines: variant k strobes 5k cycles later ----
Pos0:
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos1:
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos2:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos3:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos4:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos5:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos6:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos7:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy
Pos8:
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0           ; 3 cy
        jmp AfterPos        ; 3 cy

; ---- band tables ----
TabLo:
        .byte #<Pos4, #<Pos0, #<Pos5, #<Pos2, #<Pos8, #<Pos1, #<Pos6, #<Pos3, #<Pos7, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4, #<Pos4
TabHi:
        .byte #>Pos4, #>Pos0, #>Pos5, #>Pos2, #>Pos8, #>Pos1, #>Pos6, #>Pos3, #>Pos7, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4, #>Pos4
TabFine:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $10, $20, $30, $40, $50, $60, $70, $80, $90, $A0, $B0, $C0, $D0, $E0, $F0

        org $FFFC
        .word Start
        .word Start
