; litmus_restrobe.asm — GENERATED by scripts/gen_litmus_restrobe.py. Do not hand-edit.
; Bands of three lines: re-park, an untouched sentinel showing the parked three, then the
; measurement. The strobe SPACING is swept, because the ladder is not the same at every one.
        processor 6502
VSYNC = $00
VBLANK = $01
WSYNC = $02
NUSIZ0 = $04
NUSIZ1 = $05
COLUP0 = $06
COLUP1 = $07
COLUBK = $09
GRP0 = $1B
GRP1 = $1C
RESP0 = $10
RESP1 = $11
        org $F000
Reset:  sei
        cld
        ldx #0
        txa
Clear:  dex
        txs
        pha
        bne Clear
        lda #$00
        sta COLUBK
        lda #$0E
        sta COLUP0
        lda #$44
        sta COLUP1        ; a different colour, so the two can be told apart
        lda #$03
        sta NUSIZ0        ; three copies, sixteen apart
        sta NUSIZ1
Frame:  lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #35
VbPad:  sta WSYNC
        dex
        bne VbPad
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 21 -> x = 3c-60 = 3, the leftmost a player reaches
        lda #0
        sta VBLANK
        lda #$FF
        sta GRP0
        lda #$00
        sta GRP1          ; P1 stays dark until the two-player band
; ---- band s3 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s3 k2: 2 re-strobe(s) at cycles [29, 32] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        sta RESP0           ; write cycle 32 -> base x=36
; ---- band s3 k3: 3 re-strobe(s) at cycles [29, 32, 35] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        sta RESP0           ; write cycle 32 -> base x=36
        sta RESP0           ; write cycle 35 -> base x=45
; ---- band s3 k4: 4 re-strobe(s) at cycles [29, 32, 35, 38] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        sta RESP0           ; write cycle 32 -> base x=36
        sta RESP0           ; write cycle 35 -> base x=45
        sta RESP0           ; write cycle 38 -> base x=54
; ---- band s3 k5: 5 re-strobe(s) at cycles [29, 32, 35, 38, 41] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        sta RESP0           ; write cycle 32 -> base x=36
        sta RESP0           ; write cycle 35 -> base x=45
        sta RESP0           ; write cycle 38 -> base x=54
        sta RESP0           ; write cycle 41 -> base x=63
; ---- band s4 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s5 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s5 k2: 2 re-strobe(s) at cycles [29, 34] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        sta RESP0           ; write cycle 34 -> base x=42
; ---- band s5 k3: 3 re-strobe(s) at cycles [29, 34, 39] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        sta RESP0           ; write cycle 34 -> base x=42
        nop
        sta RESP0           ; write cycle 39 -> base x=57
; ---- band s5 k4: 4 re-strobe(s) at cycles [29, 34, 39, 44] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        sta RESP0           ; write cycle 34 -> base x=42
        nop
        sta RESP0           ; write cycle 39 -> base x=57
        nop
        sta RESP0           ; write cycle 44 -> base x=72
; ---- band s5 k5: 5 re-strobe(s) at cycles [29, 34, 39, 44, 49] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        sta RESP0           ; write cycle 34 -> base x=42
        nop
        sta RESP0           ; write cycle 39 -> base x=57
        nop
        sta RESP0           ; write cycle 44 -> base x=72
        nop
        sta RESP0           ; write cycle 49 -> base x=87
; ---- band s6 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s6 k2: 2 re-strobe(s) at cycles [29, 35] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        sta RESP0           ; write cycle 35 -> base x=45
; ---- band s6 k3: 3 re-strobe(s) at cycles [29, 35, 41] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        sta RESP0           ; write cycle 35 -> base x=45
        bit $80
        sta RESP0           ; write cycle 41 -> base x=63
; ---- band s6 k4: 4 re-strobe(s) at cycles [29, 35, 41, 47] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        sta RESP0           ; write cycle 35 -> base x=45
        bit $80
        sta RESP0           ; write cycle 41 -> base x=63
        bit $80
        sta RESP0           ; write cycle 47 -> base x=81
; ---- band s6 k5: 5 re-strobe(s) at cycles [29, 35, 41, 47, 53] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        sta RESP0           ; write cycle 35 -> base x=45
        bit $80
        sta RESP0           ; write cycle 41 -> base x=63
        bit $80
        sta RESP0           ; write cycle 47 -> base x=81
        bit $80
        sta RESP0           ; write cycle 53 -> base x=99
; ---- band s7 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s7 k2: 2 re-strobe(s) at cycles [29, 36] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        nop
        sta RESP0           ; write cycle 36 -> base x=48
; ---- band s7 k3: 3 re-strobe(s) at cycles [29, 36, 43] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        nop
        sta RESP0           ; write cycle 36 -> base x=48
        nop
        nop
        sta RESP0           ; write cycle 43 -> base x=69
; ---- band s7 k4: 4 re-strobe(s) at cycles [29, 36, 43, 50] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        nop
        sta RESP0           ; write cycle 36 -> base x=48
        nop
        nop
        sta RESP0           ; write cycle 43 -> base x=69
        nop
        nop
        sta RESP0           ; write cycle 50 -> base x=90
; ---- band s7 k5: 5 re-strobe(s) at cycles [29, 36, 43, 50, 57] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        nop
        nop
        sta RESP0           ; write cycle 36 -> base x=48
        nop
        nop
        sta RESP0           ; write cycle 43 -> base x=69
        nop
        nop
        sta RESP0           ; write cycle 50 -> base x=90
        nop
        nop
        sta RESP0           ; write cycle 57 -> base x=111
; ---- band s8 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s8 k2: 2 re-strobe(s) at cycles [29, 37] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0           ; write cycle 37 -> base x=51
; ---- band s8 k3: 3 re-strobe(s) at cycles [29, 37, 45] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0           ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0           ; write cycle 45 -> base x=75
; ---- band s8 k4: 4 re-strobe(s) at cycles [29, 37, 45, 53] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0           ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0           ; write cycle 45 -> base x=75
        bit $80
        nop
        sta RESP0           ; write cycle 53 -> base x=99
; ---- band s8 k5: 5 re-strobe(s) at cycles [29, 37, 45, 53, 61] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0           ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0           ; write cycle 45 -> base x=75
        bit $80
        nop
        sta RESP0           ; write cycle 53 -> base x=99
        bit $80
        nop
        sta RESP0           ; write cycle 61 -> base x=123
; ---- band s10 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s10 k2: 2 re-strobe(s) at cycles [29, 39] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 39 -> base x=57
; ---- band s10 k3: 3 re-strobe(s) at cycles [29, 39, 49] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 39 -> base x=57
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 49 -> base x=87
; ---- band s10 k4: 4 re-strobe(s) at cycles [29, 39, 49, 59] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 39 -> base x=57
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 49 -> base x=87
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 59 -> base x=117
; ---- band s10 k5: 5 re-strobe(s) at cycles [29, 39, 49, 59, 69] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 39 -> base x=57
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 49 -> base x=87
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 59 -> base x=117
        bit $80
        nop
        nop
        sta RESP0           ; write cycle 69 -> base x=147
; ---- band s12 k1: 1 re-strobe(s) at cycles [29] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
; ---- band s12 k2: 2 re-strobe(s) at cycles [29, 41] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 41 -> base x=63
; ---- band s12 k3: 3 re-strobe(s) at cycles [29, 41, 53] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 41 -> base x=63
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 53 -> base x=99
; ---- band s12 k4: 4 re-strobe(s) at cycles [29, 41, 53, 65] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park to x=3
        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29 -> base x=27
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 41 -> base x=63
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 53 -> base x=99
        bit $80
        nop
        nop
        nop
        sta RESP0           ; write cycle 65 -> base x=135
; ---- band two-players: P0 [29, 35, 41, 47, 53] / P1 [32, 38, 44, 50, 56] ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; re-park P0 to x=3
        sta RESP1         ; park P1 at x=12
        sta WSYNC         ; sentinel: P0's parked three (P1 is still dark)
        sta WSYNC
        lda #$FF
        sta GRP1          ; P1 lights up only for this one measurement line
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0           ; write cycle 29
        sta RESP1           ; write cycle 32
        sta RESP0           ; write cycle 35
        sta RESP1           ; write cycle 38
        sta RESP0           ; write cycle 41
        sta RESP1           ; write cycle 44
        sta RESP0           ; write cycle 47
        sta RESP1           ; write cycle 50
        sta RESP0           ; write cycle 53
        sta RESP1           ; write cycle 56
        sta WSYNC         ; P1 stays lit to the end of its measurement line
        lda #$00
        sta GRP1
        lda #0
        sta GRP0
        ldx #83
Rest:   sta WSYNC
        dex
        bne Rest
        lda #2
        sta VBLANK
        ldx #30
OsPad:  sta WSYNC
        dex
        bne OsPad
        jmp Frame
        org $FFFC
        word Reset
        word Reset
