; litmus_restrobe_objects.asm — GENERATED by scripts/gen_litmus_restrobe_objects.py.
; Do not hand-edit. Three lines per band: re-park (not a baseline), sentinel, measurement.
        processor 6502
VSYNC = $00
VBLANK = $01
WSYNC = $02
NUSIZ0 = $04
NUSIZ1 = $05
COLUP0 = $06
COLUP1 = $07
COLUPF = $08
COLUBK = $09
CTRLPF = $0A
RESP0 = $10
RESM0 = $12
RESM1 = $13
RESBL = $14
GRP0 = $1B
GRP1 = $1C
ENAM0 = $1D
ENAM1 = $1E
ENABL = $1F
        org $F000
Reset:  sei
        cld
        ldx #0
        txa
Clear:  dex
        txs
        pha
        bne Clear
        lda #$00
        sta COLUBK
        sta GRP0
        sta GRP1
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta NUSIZ0
        sta NUSIZ1
        sta CTRLPF
        lda #$0E
        sta COLUP0
        sta COLUPF
        lda #$44
        sta COLUP1
Frame:  lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #36
VbPad:  sta WSYNC
        dex
        bne VbPad
        sta WSYNC
        lda #0
        sta VBLANK
; ---- band M0 w2 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w2 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        sta RESM0       ; write cycle 37 -> base x=50
; ---- band M0 w2 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w2 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM0       ; write cycle 42 -> base x=65
; ---- band M0 w2 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w2 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 50 -> base x=89
; ---- band M0 w8 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w8 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        sta RESM0       ; write cycle 37 -> base x=50
; ---- band M0 w8 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w8 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM0       ; write cycle 42 -> base x=65
; ---- band M0 w8 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
; ---- band M0 w8 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 50 -> base x=89
; ---- band M0 w8 s8 k3 (A): park x=17, strobes at [34, 42, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        sta RESM0       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM0       ; write cycle 42 -> base x=65
        bit $80
        nop
        sta RESM0       ; write cycle 50 -> base x=89
; ---- band M1 w2 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w2 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        sta RESM1       ; write cycle 37 -> base x=50
; ---- band M1 w2 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w2 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM1       ; write cycle 42 -> base x=65
; ---- band M1 w2 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w2 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 50 -> base x=89
; ---- band M1 w8 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w8 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        sta RESM1       ; write cycle 37 -> base x=50
; ---- band M1 w8 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w8 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM1       ; write cycle 42 -> base x=65
; ---- band M1 w8 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
; ---- band M1 w8 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 50 -> base x=89
; ---- band M1 w8 s8 k3 (A): park x=17, strobes at [34, 42, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        sta RESM1       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESM1       ; write cycle 42 -> base x=65
        bit $80
        nop
        sta RESM1       ; write cycle 50 -> base x=89
; ---- band BL w2 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w2 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        sta RESBL       ; write cycle 37 -> base x=50
; ---- band BL w2 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w2 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESBL       ; write cycle 42 -> base x=65
; ---- band BL w2 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w2 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$10
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 2
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 50 -> base x=89
; ---- band BL w8 s3 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w8 s3 k2 (A): park x=17, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        sta RESBL       ; write cycle 37 -> base x=50
; ---- band BL w8 s8 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w8 s8 k2 (A): park x=17, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESBL       ; write cycle 42 -> base x=65
; ---- band BL w8 s16 k1 (A): park x=17, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
; ---- band BL w8 s16 k2 (A): park x=17, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 50 -> base x=89
; ---- band BL w8 s8 k3 (A): park x=17, strobes at [34, 42, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        sta RESBL       ; park: write cycle 26 -> x=17
        sta WSYNC         ; sentinel: the parked block alone, BL at x=17 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESBL       ; write cycle 42 -> base x=65
        bit $80
        nop
        sta RESBL       ; write cycle 50 -> base x=89
; ---- band P0 s3 k1 (A): park x=18, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
; ---- band P0 s3 k2 (A): park x=18, strobes at [34, 37] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
        sta RESP0       ; write cycle 37 -> base x=50
; ---- band P0 s8 k1 (A): park x=18, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
; ---- band P0 s8 k2 (A): park x=18, strobes at [34, 42] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESP0       ; write cycle 42 -> base x=65
; ---- band P0 s16 k1 (A): park x=18, strobes at [34] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
; ---- band P0 s16 k2 (A): park x=18, strobes at [34, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
        bit $80
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 50 -> base x=89
; ---- band P0 s8 k3 (A): park x=18, strobes at [34, 42, 50] ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        sta RESP0       ; park: write cycle 26 -> x=18
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=18 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 34 -> base x=41
        bit $80
        nop
        sta RESP0       ; write cycle 42 -> base x=65
        bit $80
        nop
        sta RESP0       ; write cycle 50 -> base x=89
; ---- band M0 w8 mid+6 (B): park x=50, one strobe at cycle 39 -> x=56 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM0       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 39 -> base x=56
; ---- band M0 w8 mid+9 (B): park x=50, one strobe at cycle 40 -> x=59 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM0       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 40 -> base x=59
; ---- band M0 w8 mid+12 (B): park x=50, one strobe at cycle 41 -> x=62 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM0       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 41 -> base x=62
; ---- band M0 w8 mid+15 (B): park x=50, one strobe at cycle 42 -> x=65 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ0
        lda #$02
        sta ENAM0 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM0       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M0 at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM0       ; write cycle 42 -> base x=65
; ---- band M1 w8 mid+6 (B): park x=50, one strobe at cycle 39 -> x=56 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM1       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 39 -> base x=56
; ---- band M1 w8 mid+9 (B): park x=50, one strobe at cycle 40 -> x=59 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM1       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 40 -> base x=59
; ---- band M1 w8 mid+12 (B): park x=50, one strobe at cycle 41 -> x=62 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM1       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 41 -> base x=62
; ---- band M1 w8 mid+15 (B): park x=50, one strobe at cycle 42 -> x=65 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta NUSIZ1
        lda #$02
        sta ENAM1 
        bit $80
        nop
        nop
        nop
        nop
        sta RESM1       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, M1 at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESM1       ; write cycle 42 -> base x=65
; ---- band BL w8 mid+6 (B): park x=50, one strobe at cycle 39 -> x=56 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        bit $80
        nop
        nop
        nop
        nop
        sta RESBL       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, BL at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 39 -> base x=56
; ---- band BL w8 mid+9 (B): park x=50, one strobe at cycle 40 -> x=59 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        bit $80
        nop
        nop
        nop
        nop
        sta RESBL       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, BL at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 40 -> base x=59
; ---- band BL w8 mid+12 (B): park x=50, one strobe at cycle 41 -> x=62 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        bit $80
        nop
        nop
        nop
        nop
        sta RESBL       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, BL at x=50 width 8
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 41 -> base x=62
; ---- band BL w8 mid+15 (B): park x=50, one strobe at cycle 42 -> x=65 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$30
        sta CTRLPF
        lda #$02
        sta ENABL 
        bit $80
        nop
        nop
        nop
        nop
        sta RESBL       ; park: write cycle 37 -> x=50
        sta WSYNC         ; sentinel: the parked block alone, BL at x=50 width 8
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESBL       ; write cycle 42 -> base x=65
; ---- band P0 mid+6 (B): park x=51, one strobe at cycle 39 -> x=56 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        bit $80
        nop
        nop
        nop
        nop
        sta RESP0       ; park: write cycle 37 -> x=51
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=51 width 1
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 39 -> base x=56
; ---- band P0 mid+9 (B): park x=51, one strobe at cycle 40 -> x=59 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        bit $80
        nop
        nop
        nop
        nop
        sta RESP0       ; park: write cycle 37 -> x=51
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=51 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 40 -> base x=59
; ---- band P0 mid+12 (B): park x=51, one strobe at cycle 41 -> x=62 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        bit $80
        nop
        nop
        nop
        nop
        sta RESP0       ; park: write cycle 37 -> x=51
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=51 width 1
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 41 -> base x=62
; ---- band P0 mid+15 (B): park x=51, one strobe at cycle 42 -> x=65 ----
        sta WSYNC
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        lda #$00
        sta NUSIZ0
        lda #$FF
        sta GRP0  
        bit $80
        nop
        nop
        nop
        nop
        sta RESP0       ; park: write cycle 37 -> x=51
        sta WSYNC         ; sentinel: the parked block alone, P0 at x=51 width 1
        sta WSYNC
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0       ; write cycle 42 -> base x=65
        lda #$00
        sta ENAM0
        sta ENAM1
        sta ENABL
        sta GRP0
        ldx #6
Rest:   sta WSYNC
        dex
        bne Rest
        lda #2
        sta VBLANK
        ldx #30
OsPad:  sta WSYNC
        dex
        bne OsPad
        jmp Frame
        org $FFFC
        word Reset
        word Reset
