; litmus_sprite_place — where RESP and RESM put an object, when a write reaches the copy it is
; meant for, and what a strobe does NOT do on the line it runs on.
;
; GENERATED by scripts/gen_litmus_sprite_place.py — every band lands a strobe or a write on an
; exact cycle and the padding that gets it there is arithmetic. Edit the generator, not this.
;
; These are the numbers a kernel author needs BEFORE deciding whether a shape wider than eight
; pixels can be drawn at all. None of them was written down anywhere in this repository until
; 2026-08-21; they were re-derived from throwaway probes twice in one session.
;
;   1. a RESP strobe whose WRITE cycle is c puts a NORMAL-width player at x = 3c - 60
;   2. a RESM strobe puts a missile at x = 3c - 61 — one clock further LEFT from the same cycle
;   3. so RESM three cycles after RESP puts the missile at EXACTLY player + 8, which is where an
;      8 px player stops drawing. Two RESP strobes never can: three cycles is the shortest gap
;      between two stores and three cycles is nine colour clocks.
;   4. a missile follows its player's NUSIZ copies
;   5. a strobe does not draw the new position on the line it runs on
;   6. a GRP write takes effect at screen x = 3w - 64, so it needs FOUR colour clocks of margin
;      ahead of the copy it feeds and not one more
;   7. a normal-width player cannot be strobed left of x=3
;   9. a missile and the ball are clamped at x=2 and a player at x=3, and each clamp spans a
;      WINDOW of write cycles, not one
;  10. a NUSIZ copy past 160 wraps to the left edge and draws there on the same line
;   8. and a strobe cancels the pending draw of the FIRST copy ONLY — the copies NUSIZ makes at
;      +32 and +64 are triggered from the reset position and still land on the strobe line
;
; LAYOUT. Eleven bands of four scanlines each. Band b's lines are 4b..4b+3, counting from the
; first band's line 0; the grader finds that line and indexes from it.
;
;   band  line  what it shows
;    0     1-3  RESP0 write cycle 24            -> P0 at 12
;    1     1-3  RESP0 write cycle 40            -> P0 at 60
;    2     1-3  RESM0 write cycle 24            -> M0 at 11
;    3     1-3  RESM0 write cycle 40            -> M0 at 59
;    4     1-3  RESP0 at 30 then RESM0 at 33    -> P0 30..37 and M0 38..41, abutting
;    5     1-3  the same with NUSIZ0 = $26      -> three of those, 32 px apart
;    6     1-3  P0 lit across its own RESP0     -> old position on the strobe line, new one after
;    7     1-3  GRP0 <- 0 on cycle 43 / 42 / 41 -> copy 1 keeps 3 px / is clean / is clean
;    8     1,3  RESP0 write cycle 17 and 21     -> both land on x=3, the clamp
;    9     1,3  RESP0 write cycle 22 and 25     -> x=6 and x=15, the formula above the clamp
;   10     2,3  a mid-line strobe               -> copy 0 gone, copies 1 and 2 drawn anyway
;   11     1,3  RESM0 write cycle 17 and 21     -> both land on x=2, the missile's clamp
;   12     1,3  RESM0 write cycle 22 and 25     -> x=5 and x=14, the formula above the clamp
;   13     1,3  RESBL write cycle 24 and 40     -> x=11 and x=59: the ball IS a missile grid
;   14     1,3  RESBL write cycle 17 and 21     -> both land on x=2, the ball's clamp
;   15     1-3  P0 at x=120 with three copies   -> 120, 152 and a WRAPPED one at 24

        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUBK  = $09
RESP0   = $10
RESM0   = $12
GRP0    = $1B
ENAM0   = $1D
RESBL   = $14
ENABL   = $1F
CTRLPF  = $0A
COLUPF  = $08
HMCLR   = $2B

        org $F000
Reset:
        sei
        cld
        ldx #0
        txa
Clr:    dex
        txs
        pha
        bne Clr
        sta HMCLR       ; nothing here ever strobes HMOVE — every position is RESP/RESM alone
        lda #$00
        sta COLUBK
        lda #$0E
        sta COLUP0
        sta COLUPF      ; the ball draws in COLUPF, and bands 13-14 need to see it
        lda #$20
        sta CTRLPF      ; ball 4 px wide

Frame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
Vb:     sta WSYNC
        dex
        bne Vb
        lda #0
        sta VBLANK

; ---- band 0: RESP0 write cycle 24 -> P0 at 12 ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$00        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 24
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0

; ---- band 1: RESP0 write cycle 40 -> P0 at 60 ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$00        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 40
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0
        sta WSYNC
        lda #$80
        sta GRP0
        lda #$00
        sta ENAM0

; ---- band 2: RESM0 write cycle 24 -> M0 at 11 ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$00        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESM0      ; write cycle 24
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0

; ---- band 3: RESM0 write cycle 40 -> M0 at 59 ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$00        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESM0      ; write cycle 40
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$00
        sta GRP0
        lda #$02
        sta ENAM0

; ---- band 4: RESP0 at 30 then RESM0 at 33 -> P0 30..37 + M0 38..41 ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$20        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 30
        sta RESM0      ; write cycle 33
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0

; ---- band 5: the same, NUSIZ0=$26: three copies 32 apart ----
        sta WSYNC
        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken
        sta GRP0        ; 3   for the result
        sta ENAM0       ; 3
        lda #$26        ; 2
        sta NUSIZ0      ; 3
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 30
        sta RESM0      ; write cycle 33
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$FF
        sta GRP0
        lda #$02
        sta ENAM0

; ---- band 6: a strobe does not draw the NEW position on its own line ----
        sta WSYNC
        lda #0
        sta ENAM0
        sta NUSIZ0      ; back to one copy, no missile
        lda #$80
        sta GRP0        ; P0 is LIT for all of this band, at x=30 left over from band 5
        sta WSYNC
        sta WSYNC
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 40  -> x=60, but NOT on this line
        sta WSYNC

; ---- band 7: how late a GRP write can be and still reach its copy ----
; P0 sits at x=30 with three copies, at 30, 62 and 94. Each line below puts GRP0 up as $FF in
; HBLANK and drops it to $00 partway across. Copy 0 has already drawn; whether copy 1 at x=62
; comes out clean says whether the write reached it. 3w-68 steps by three, so 43, 42 and 41
; land the write at x=61, 58 and 55 — one, four and seven clocks ahead of copy 1.
        sta WSYNC
        lda #$06
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 30  -> x=30, copies at 30/62/94
        sta WSYNC
        lda #$FF
        sta GRP0        ; up in HBLANK, so copy 0 at x=30 always draws
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        lda #0
        sta GRP0        ; write cycle 43, lands at x=61, 1 clocks before copy 1
        sta WSYNC
        lda #$FF
        sta GRP0        ; up in HBLANK, so copy 0 at x=30 always draws
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        lda #0
        sta GRP0        ; write cycle 42, lands at x=58, 4 clocks before copy 1
        sta WSYNC
        lda #$FF
        sta GRP0        ; up in HBLANK, so copy 0 at x=30 always draws
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        lda #0
        sta GRP0        ; write cycle 41, lands at x=55, 7 clocks before copy 1

; ---- band 8: a normal-width player cannot be strobed left of x=3 ----
        sta WSYNC
        lda #$00
        sta NUSIZ0      ; one copy, normal width
        lda #0
        sta GRP0
        bit $80         ; 3
        nop             ; 2
        sta RESP0      ; write cycle 17  -> the clamp, not 3c-60
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC
        lda #$00
        sta NUSIZ0      ; one copy, normal width
        lda #0
        sta GRP0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 21  -> the clamp, not 3c-60
        sta WSYNC
        lda #$80
        sta GRP0

; ---- band 9: and above the clamp the formula holds ----
        sta WSYNC
        lda #0
        sta GRP0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 22  -> x=6 = 3*22 - 60
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC
        lda #0
        sta GRP0
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 25  -> x=15 = 3*25 - 60
        sta WSYNC
        lda #$80
        sta GRP0

; ---- band 10: a strobe cancels the FIRST copy only ----
; P0 is lit and parked at x=42 with three copies, at 42, 74 and 106. The third line strobes it
; to x=24 while the beam is at 16 — ahead of every one of those. If a strobe simply moved the
; object, x=24 would draw; if it cancelled the object, nothing would. What happens is neither:
; copy 0 is gone and the copies at 24+32 and 24+64 land anyway, because they are triggered from
; the reset position and the counter reaches them before the line ends.
        sta WSYNC
        lda #$06
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 34  -> x=42, copies at 42/74/106
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 28  -> x=24 while the beam is at 16
        sta WSYNC

; ---- band 11: a missile is clamped at x=2, and the clamp is a WINDOW of write cycles ----
; Band 8 showed a player clamped at 3. A missile stops one clock further LEFT, at 2 — a place no
; player can be reached to by any strobe or any copy of one. Both cycles below land on it, and
; that the clamp spans SEVERAL cycles rather than one is the load-bearing part: it is what lets
; an object at the wall be strobed clear of another four pixels to its right, which anywhere
; else on the grid would be one cycle away and therefore impossible for two 3-cycle stores.
        sta WSYNC
        lda #$00
        sta NUSIZ0      ; one copy, missile 1 px
        lda #0
        sta GRP0
        sta ENAM0
        nop             ; 2
        sta RESM0      ; write cycle 17  -> the clamp at x=2, not 3c-61
        sta WSYNC
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #$00
        sta NUSIZ0      ; one copy, missile 1 px
        lda #0
        sta GRP0
        sta ENAM0
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESM0      ; write cycle 21  -> the clamp at x=2, not 3c-61
        sta WSYNC
        lda #$02
        sta ENAM0

; ---- band 12: and above its clamp the missile formula holds ----
        sta WSYNC
        lda #0
        sta ENAM0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESM0      ; write cycle 22  -> x=5 = 3*22 - 61
        sta WSYNC
        lda #$02
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESM0      ; write cycle 25  -> x=14 = 3*25 - 61
        sta WSYNC
        lda #$02
        sta ENAM0

; ---- band 13: the BALL places exactly like a missile ----
; The fifth movable object, and the one this catalogue had never measured. RESBL obeys the same
; x = 3c - 61 as RESM, so the ball shares the missile's grid -- one clock left of the player's --
; and can stand in for a missile wherever a row has run out of them.
        sta WSYNC
        lda #0
        sta ENABL
        sta ENAM0       ; band 12's missile off, so only the ball is in this band
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESBL      ; write cycle 24  -> x=11 = 3*24 - 61, same as RESM
        sta WSYNC
        lda #$02
        sta ENABL
        sta WSYNC
        lda #0
        sta ENABL
        sta ENAM0       ; band 12's missile off, so only the ball is in this band
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESBL      ; write cycle 40  -> x=59 = 3*40 - 61, same as RESM
        sta WSYNC
        lda #$02
        sta ENABL

; ---- band 14: and the ball is clamped at x=2, like a missile and unlike a player ----
        sta WSYNC
        lda #0
        sta ENABL
        sta ENAM0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        sta RESBL      ; write cycle 17  -> the clamp at x=2
        sta WSYNC
        lda #$02
        sta ENABL
        sta WSYNC
        lda #0
        sta ENABL
        sta ENAM0
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESBL      ; write cycle 21  -> the clamp at x=2
        sta WSYNC
        lda #$02
        sta ENABL

; ---- band 15: a NUSIZ copy past 160 WRAPS and draws at the left edge, on the same line ----
; P0 is strobed to x=120 with three copies, which NUSIZ puts at 120, 152 and 184. There is no
; 184 on a 160-clock line: the position counter folds it to 24 and the copy draws THERE, on the
; same scanline, with whatever GRP0 held when the beam passed. So an object strobed on the right
; of the screen can put a copy on the far left -- including at positions no strobe can reach.
        sta WSYNC
        lda #0
        sta ENABL
        sta ENAM0
        lda #$06
        sta NUSIZ0      ; three copies, 32 apart
        bit $80         ; 3
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        nop             ; 2
        sta RESP0      ; write cycle 60  -> x=120; copies at 120, 152 and 184->24
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC
        lda #$80
        sta GRP0
        sta WSYNC

        lda #0
        sta GRP0
        sta ENAM0
        ldx #127
Rest:   sta WSYNC
        dex
        bne Rest
        lda #2
        sta VBLANK
        ldx #30
Os:     sta WSYNC
        dex
        bne Os
        jmp Frame

        org $FFFC
        word Reset
        word Reset
