; litmus_missile_novdel — missiles have no vertical-delay path; the ball does
;   (GENERATED by scripts/gen_litmus_missile_novdel.py — edit that, not this file)
;
; Closes the 📖 'Missiles have no vertical delay'. Read against the ball, which does
; have one: with VDELBL set, ENABL's new copy waits for a GRP1 write. The missile has
; no such pair, so it lights immediately under the same conditions.
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUP0  = $06
COLUPF  = $08
COLUBK  = $09
RESM0   = $12
RESBL   = $14
GRP0    = $1B
GRP1    = $1C
ENAM0   = $1D
ENABL   = $1F
VDELP0  = $25
VDELP1  = $26
VDELBL  = $27
HMCLR   = $2B

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        sta HMCLR
        lda #$0E
        sta COLUP0          ; white = missile 0
        lda #$46
        sta COLUPF          ; red   = ball

NextFrame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #2
        sta VBLANK
        sta WSYNC
        ldx #6
Ma:     dex
        bne Ma
        sta RESM0
        ldx #8
Mb:     dex
        bne Mb
        sta RESBL           ; the two sit in different columns
        ldx #35
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ; ===== A  all VDEL set, both enabled, no latch =====
        sta WSYNC
        lda #0
        sta ENAM0
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1
        sta GRP0
        sta WSYNC
        lda #1
        sta VDELBL          ; the ball will display its OLD copy
        lda #2
        sta ENAM0           ; missile: no old/new pair to wait on
        sta ENABL           ; ball: new copy set, old still zero
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== B  VDELBL clear: both must be lit =====
        sta WSYNC
        lda #0
        sta ENAM0
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1
        sta GRP0
        sta WSYNC
        lda #2
        sta ENAM0
        sta ENABL
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== C  VDELBL set, then GRP1 latches the ball =====
        sta WSYNC
        lda #0
        sta ENAM0
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1
        sta GRP0
        sta WSYNC
        lda #1
        sta VDELBL
        lda #2
        sta ENAM0
        sta ENABL
        lda #0
        sta GRP1            ; latches ENABL new->old
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== clear before the filler =====
        sta WSYNC
        lda #0
        sta ENAM0
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1
        sta GRP0
        ldx #161
Fill:   sta WSYNC
        dex
        bne Fill
        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

        org $FFFC
        .word Start
        .word Start
