; litmus_restrobe.asm — GENERATED by scripts/gen_litmus_restrobe.py. Do not hand-edit.
; Six bands of three lines: k re-strobes, then an untouched line, then a line that re-parks.
        processor 6502
VSYNC = $00
VBLANK = $01
WSYNC = $02
NUSIZ0 = $04
COLUP0 = $06
COLUBK = $09
GRP0 = $1B
RESP0 = $10
        org $F000
Reset:  sei
        cld
        ldx #0
        txa
Clear:  dex
        txs
        pha
        bne Clear
        lda #$00
        sta COLUBK
        lda #$0E
        sta COLUP0
        lda #$03
        sta NUSIZ0        ; three copies, sixteen apart
Frame:  lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #35
VbPad:  sta WSYNC
        dex
        bne VbPad
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 21 -> x = 3c-60 = 3, the leftmost a player reaches
        lda #0
        sta VBLANK
        lda #$FF
        sta GRP0
; ---- band 0: 0 re-strobe(s) ----
        sta WSYNC
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
; ---- band 1: 1 re-strobe(s) ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 29 -> base x=27
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
; ---- band 2: 2 re-strobe(s) ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0         ; write cycle 37 -> base x=51
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
; ---- band 3: 3 re-strobe(s) ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0         ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0         ; write cycle 45 -> base x=75
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
; ---- band 4: 4 re-strobe(s) ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0         ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0         ; write cycle 45 -> base x=75
        bit $80
        nop
        sta RESP0         ; write cycle 53 -> base x=99
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
; ---- band 5: 5 re-strobe(s) ----
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; write cycle 29 -> base x=27
        bit $80
        nop
        sta RESP0         ; write cycle 37 -> base x=51
        bit $80
        nop
        sta RESP0         ; write cycle 45 -> base x=75
        bit $80
        nop
        sta RESP0         ; write cycle 53 -> base x=99
        bit $80
        nop
        sta RESP0         ; write cycle 61 -> base x=123
        sta WSYNC         ; untouched: the parked three
        sta WSYNC
        bit $80
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        sta RESP0         ; back to x=3
        lda #0
        sta GRP0
        ldx #174
Rest:   sta WSYNC
        dex
        bne Rest
        lda #2
        sta VBLANK
        ldx #30
OsPad:  sta WSYNC
        dex
        bne OsPad
        jmp Frame
        org $FFFC
        word Reset
        word Reset
