; litmus_vdel_cross — VDEL's write-triggered cross-copy between GRP0/GRP1/ENABL
;   (GENERATED by scripts/gen_litmus_vdel_cross.py — edit that, not this file)
;
; Closes docs/fundamentals-audit.md:70. Claim (Stella PG 6.D): writing GRP0 copies
; P1's new->old; writing GRP1 copies P0's new->old AND ENABL's new->old.
; Bands A and B differ by ONE instruction — GRP0 vs GRP1 — and the ball's visibility
; is the reading.
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUP0  = $06
COLUP1  = $07
COLUPF  = $08
COLUBK  = $09
RESP0   = $10
RESP1   = $11
RESBL   = $14
GRP0    = $1B
GRP1    = $1C
ENABL   = $1F
VDELP0  = $25
VDELP1  = $26
VDELBL  = $27
HMCLR   = $2B
scratch = $82

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        sta HMCLR
        lda #$0E
        sta COLUP0          ; white  = P0
        lda #$B6
        sta COLUP1          ; green  = P1
        lda #$46
        sta COLUPF          ; red    = ball

NextFrame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #2
        sta VBLANK
        ; place the three objects apart so each colour has its own column
        sta WSYNC
        ldx #4
Pa:     dex
        bne Pa
        sta RESP0
        ldx #4
Pb:     dex
        bne Pb
        sta RESP1
        ldx #4
Pc:     dex
        bne Pc
        sta RESBL
        ldx #35
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ; ===== A  VDELBL, ENABL, then GRP0 -> ball must stay OFF =====
        sta WSYNC
        lda #0
        sta GRP0
        sta GRP1
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1            ; latch old := 0 (ball + P0)
        sta GRP0            ; latch old := 0 (P1)
        sta WSYNC
        lda #1
        sta VDELBL          ; display the OLD enable
        lda #2
        sta ENABL           ; NEW enable = on; old is still off
        lda #$00
        sta GRP0            ; writing GRP0 must NOT latch the ball
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== B  VDELBL, ENABL, then GRP1 -> ball must turn ON =====
        sta WSYNC
        lda #0
        sta GRP0
        sta GRP1
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1            ; latch old := 0 (ball + P0)
        sta GRP0            ; latch old := 0 (P1)
        sta WSYNC
        lda #1
        sta VDELBL
        lda #2
        sta ENABL
        lda #$00
        sta GRP1            ; writing GRP1 copies ENABL new->old
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== C  VDELP0, GRP0=$FF, GRP1 latches it, GRP0=$00 -> P0 shows $FF =====
        sta WSYNC
        lda #0
        sta GRP0
        sta GRP1
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1            ; latch old := 0 (ball + P0)
        sta GRP0            ; latch old := 0 (P1)
        sta WSYNC
        lda #1
        sta VDELP0
        lda #$FF
        sta GRP0            ; new = $FF
        lda #$00
        sta GRP1            ; copies P0 new->old, so old = $FF
        sta GRP0            ; new = $00; the display uses old
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== D  VDELP1, GRP1=$FF, GRP0 latches it, GRP1=$00 -> P1 shows $FF =====
        sta WSYNC
        lda #0
        sta GRP0
        sta GRP1
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        sta GRP1            ; latch old := 0 (ball + P0)
        sta GRP0            ; latch old := 0 (P1)
        sta WSYNC
        lda #1
        sta VDELP1
        lda #$FF
        sta GRP1            ; new = $FF
        lda #$00
        sta GRP0            ; copies P1 new->old, so old = $FF
        sta GRP1            ; new = $00; the display uses old
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; ===== clear before the filler =====
        sta WSYNC
        lda #0
        sta GRP0
        sta GRP1
        sta ENABL
        sta VDELP0
        sta VDELP1
        sta VDELBL
        ldx #159
Fill:   sta WSYNC
        dex
        bne Fill
        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

        org $FFFC
        .word Start
        .word Start
