; litmus_resmp — where RESMP leaves the missile when the lock is released
;   (GENERATED by scripts/gen_litmus_resmp.py — edit that, not this file)
;
; Closes docs/fundamentals-audit.md:53, which says 'release leaves M centered on P
; (Stella PG). ⬜ exact lock offset' — the ⬜ is harness saying it does not know the
; number, while roms/techniques/bullets.asm:3 states +4px. Neither was graded.
;
; The player is drawn on one line and the missile on the next, because they share
; COLUP0 and a line carrying both cannot be read apart by colour.
;
; 12 bands x 7 lines = 84 picture lines, 108 blank.
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUBK  = $09
RESP0   = $10
GRP0    = $1B
ENAM0   = $1D
HMCLR   = $2B
RESMP0  = $28
scratch = $82

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        sta HMCLR
        lda #$0E
        sta COLUP0

NextFrame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #2
        sta VBLANK
        ldx #37
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ; --- NUSIZ0=0x0 (1x, 8 clocks), position +0 ---
        sta WSYNC
        lda #$00
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x0 (1x, 8 clocks), position +1 ---
        sta WSYNC
        lda #$00
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x0 (1x, 8 clocks), position +2 ---
        sta WSYNC
        lda #$00
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x0 (1x, 8 clocks), position +3 ---
        sta WSYNC
        lda #$00
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x5 (2x, 16 clocks), position +0 ---
        sta WSYNC
        lda #$05
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x5 (2x, 16 clocks), position +1 ---
        sta WSYNC
        lda #$05
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x5 (2x, 16 clocks), position +2 ---
        sta WSYNC
        lda #$05
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x5 (2x, 16 clocks), position +3 ---
        sta WSYNC
        lda #$05
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x7 (4x, 32 clocks), position +0 ---
        sta WSYNC
        lda #$07
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x7 (4x, 32 clocks), position +1 ---
        sta WSYNC
        lda #$07
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x7 (4x, 32 clocks), position +2 ---
        sta WSYNC
        lda #$07
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ; --- NUSIZ0=0x7 (4x, 32 clocks), position +3 ---
        sta WSYNC
        lda #$07
        sta NUSIZ0
        lda #0
        sta GRP0
        sta ENAM0
        ; --- strobe RESP0, then lock the missile to the player ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        sta RESP0
        lda #2
        sta RESMP0          ; D1 = lock M0 to P0
        ; --- the lock has to be HELD for a full scanline. The snap fires when the
        ;     player's scan counter reaches a particular pixel (Gopher2600
        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,
        ;     pixel 5 count 3 at 4x), which only comes round once the position counter
        ;     has walked the line. A band that locks and releases inside the same line
        ;     never snaps: the first version of this fixture did that and read a
        ;     constant 17 in every band.
        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first
        ;     said the player had to be drawn; removing the graphics byte and keeping
        ;     the held line leaves every measurement unchanged, while keeping the
        ;     graphics and dropping the held line breaks three of the four gradings.
        sta WSYNC
        lda #$FF
        sta GRP0            ; full bar: the scan counter runs the whole width
        sta WSYNC           ; one full line of drawing = the snap
        ; --- release; the missile keeps where the lock left it ---
        lda #0
        sta RESMP0
        ; --- player alone (one pixel, so its left edge is unambiguous) ---
        sta WSYNC
        lda #$80
        sta GRP0
        ; --- missile alone: they share COLUP0, so they cannot share a line ---
        sta WSYNC
        lda #0
        sta GRP0
        lda #2
        sta ENAM0
        sta WSYNC
        lda #0
        sta ENAM0
        ldx #108
Fill:   sta WSYNC
        dex
        bne Fill
        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

        org $FFFC
        .word Start
        .word Start
