; litmus_respx_phase — the reset-strobe phase for RESP0 / RESM0 / RESBL
;   (GENERATED by scripts/gen_litmus_respx_phase.py — edit that, not this file)
;
; Closes docs/fundamentals-audit.md:43, which harness marks 📖 = documented, NOT
; measured. Claim under test: 'counter reset -> first visible copy appears 5px right
; of the reset' (Towers, TIA Hardware Notes), stated for RESPx.
;
; One band per strobe cycle; consecutive bands strobe 1 CPU cycle = 3 colour clocks
; later. The grading test fits x = 3*c + k and reports k per object, so the phase is
; measured, and measured separately for the 8-clock player and the 1-clock missile
; and ball.
;
; 48 bands x 4 lines = 192 picture lines, 0 blank.
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUP1  = $07
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
RESP0   = $10
RESM1   = $13
RESBL   = $14
GRP0    = $1B
ENAM1   = $1E
ENABL   = $1F
HMCLR   = $2B
scratch = $82

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        sta HMCLR           ; every HMxx zero for the whole run
        sta CTRLPF          ; ball 1 clock wide, no reflect, no score
        sta NUSIZ0          ; player 1x, missile 1 clock
        lda #$0E
        sta COLUP0          ; white: player and missile
        lda #$46
        sta COLUPF          ; red: ball
        lda #$B6
        sta COLUP1          ; green: missile 1
        lda #$80
        sta GRP0            ; one pixel, leftmost bit of the player
        lda #2
        sta ENAM1
        sta ENABL

NextFrame:
        lda #2
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        lda #2
        sta VBLANK
        ldx #37
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ; --- RESP0, +2 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +3 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +4 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +5 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +6 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +7 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +8 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +9 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +10 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +11 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +12 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +13 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +14 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +15 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +16 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESP0, +17 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESP0           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +2 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +3 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +4 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +5 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +6 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +7 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +8 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +9 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +10 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +11 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +12 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +13 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +14 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +15 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +16 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESM1, +17 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESM1           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +2 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +3 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +4 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +5 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +6 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +7 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +8 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +9 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +10 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +11 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +12 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +13 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +14 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +15 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +16 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC
        ; --- RESBL, +17 cy ---
        sta WSYNC
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        dec scratch         ; 5 cy
        bit scratch         ; 3 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        nop                 ; 2 cy
        sta RESBL           ; strobe
        sta WSYNC
        sta WSYNC
        sta WSYNC

        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

        org $FFFC
        .word Start
        .word Start
