; asym playfield — generated by pkg/playfield.GenerateAsymmetricASM
; 非対称(左右独立) playfield 静止画。行数=48 行高=4。1ライン内で PF を A→B に詰め替え（ABB転写）。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
PFHGT   = $80

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #0
        sta CTRLPF      ; reflect 無し（非対称はライン内の詰め替えで作る）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
VBlank: sta WSYNC
        dex
        bne VBlank
        lda #$0E
        sta COLUPF      ; 睡蓮（frame 固定の前景色）
        lda #0
        sta VBLANK

        ldx #47
        lda #4
        sta PFHGT
PFLoop:
        sta WSYNC                 ; (0)
        lda BGColors,x            ; (4)
        sta COLUBK                ; (7)  水（per-row、HBLANK 中＝行全体に効く）
        lda PF0DataA,x            ; (11)
        sta PF0                   ; (14)
        lda PF1DataA,x            ; (18)
        sta PF1                   ; (21)
        lda PF2DataA,x            ; (25)
        sta PF2                   ; (28)  左半確定
        lda PF0DataB,x            ; (32)
        tay                       ; (34)  PF0B を Y に退避
        lda PF1DataB,x            ; (38)
        sta PF1                   ; (41)  右半 PF1
        sty PF0                   ; (44)  右半 PF0
        lda PF2DataB,x            ; (48)
        sta PF2                   ; (51)  右半 PF2
        dec PFHGT                 ; (56)
        bne PFSkip                ; (58/59)
        lda #4                   ; (60)
        sta PFHGT                 ; (63)
        dex                       ; (65)
        cpx #$FF                  ; (67)
        beq PFDone                ; (69)
PFSkip:
        jmp PFLoop                ; (72)
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        ldx #30
OScan:  sta WSYNC
        dex
        bne OScan
        jmp NextFrame

PF0DataA
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $80
        .byte $80
        .byte $C0
        .byte $E0
        .byte $F0
        .byte $F0

PF1DataA
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $01
        .byte $03
        .byte $07
        .byte $07
        .byte $0F
        .byte $1E
        .byte $3C
        .byte $3C
        .byte $78
        .byte $F0
        .byte $E0
        .byte $E0
        .byte $C0
        .byte $80
        .byte $00
        .byte $00

PF2DataA
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $80
        .byte $C0
        .byte $C0
        .byte $E0
        .byte $F0
        .byte $78
        .byte $78
        .byte $3C
        .byte $1E
        .byte $0F
        .byte $0F
        .byte $07
        .byte $03
        .byte $01
        .byte $01
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PF0DataB
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $80
        .byte $C0
        .byte $E0
        .byte $E0
        .byte $F0
        .byte $70
        .byte $30
        .byte $30
        .byte $10
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PF1DataB
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $01
        .byte $03
        .byte $03
        .byte $07
        .byte $0F
        .byte $1E
        .byte $1E
        .byte $3C
        .byte $78
        .byte $F0
        .byte $F0
        .byte $E0
        .byte $C0
        .byte $80
        .byte $80
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PF2DataB
        .byte $78
        .byte $3C
        .byte $1E
        .byte $1E
        .byte $0F
        .byte $07
        .byte $03
        .byte $03
        .byte $01
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

BGColors
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $84

        org $FFFC
        .word Start
        .word Start
