; Monet full scene — pkg/playfield.GenerateMonetFullASM
; 水面(per-scanline COLUBK) + 流れる睡蓮(player0/NUSIZ/HMP0) + 操作カエル(player1/SWCHA)。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
NUSIZ1  = $05
COLUP0  = $06
COLUP1  = $07
COLUBK  = $09
RESP0   = $10
RESP1   = $11
GRP0    = $1B
GRP1    = $1C
HMP0    = $20
HMP1    = $21
HMOVE   = $2A
CXCLR   = $2C
CXPPMM  = $37
SWCHA   = $0280

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #$C8
        sta COLUP0
        lda #$1C
        sta COLUP1
        lda #$03
        sta NUSIZ0
        lda #$00
        sta NUSIZ1

        sta WSYNC        ; 睡蓮(player0) 初期 X
        ldx #14
P0d:    dex
        bne P0d
        sta RESP0
        sta WSYNC        ; カエル(player1) 初期 X（中央寄り）
        ldx #26
P1d:    dex
        bne P1d
        sta RESP1
        lda #$F0
        sta HMP0         ; 睡蓮の一定ドリフト

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC

        ; --- 入力 → HMP1（カエル左右）---
        ldx #$00
        lda SWCHA
        and #$80
        bne CkL
        ldx #$E0         ; 右 2px
CkL:    lda SWCHA
        and #$40
        bne SetH
        ldx #$20         ; 左 2px
SetH:   stx HMP1

        sta WSYNC
        sta HMOVE        ; 両プレイヤーへ累積モーション適用
        sta CXCLR        ; 衝突ラッチをクリア（この frame の衝突を新たに取る）
        ldx #36
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ldy #0
VL:     sta WSYNC
        lda GRP0Tab,y    ; 睡蓮
        sta GRP0
        lda GRP1Tab,y    ; カエル
        sta GRP1
        lda BGTab,y      ; 水
        sta COLUBK
        iny
        cpy #192
        bne VL
        lda #0
        sta GRP0
        sta GRP1

        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

GRP0Tab
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $3C
        .byte $7E
        .byte $FF
        .byte $FF
        .byte $FF
        .byte $FF
        .byte $7E
        .byte $3C
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

GRP1Tab
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $24
        .byte $7E
        .byte $FF
        .byte $FF
        .byte $BD
        .byte $7E
        .byte $24
        .byte $42
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

BGTab
        .byte $78
        .byte $78
        .byte $78
        .byte $78
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $78
        .byte $78
        .byte $78
        .byte $78
        .byte $96
        .byte $96
        .byte $96
        .byte $96
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $8C
        .byte $8C
        .byte $8C
        .byte $8C
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $54
        .byte $54
        .byte $54
        .byte $54
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $B8
        .byte $B8
        .byte $B8
        .byte $B8
        .byte $BA
        .byte $BA
        .byte $BA
        .byte $BA
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $B4
        .byte $B4
        .byte $B4
        .byte $B4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $88
        .byte $88
        .byte $88
        .byte $88
        .byte $86
        .byte $86
        .byte $86
        .byte $86
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $96
        .byte $96
        .byte $96
        .byte $96
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $98
        .byte $98
        .byte $98
        .byte $98
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $64
        .byte $64
        .byte $64
        .byte $64
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $64
        .byte $64
        .byte $64
        .byte $64
        .byte $BC
        .byte $BC
        .byte $BC
        .byte $BC
        .byte $C8
        .byte $C8
        .byte $C8
        .byte $C8
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $74
        .byte $74
        .byte $74
        .byte $74
        .byte $88
        .byte $88
        .byte $88
        .byte $88
        .byte $7A
        .byte $7A
        .byte $7A
        .byte $7A
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $94
        .byte $94
        .byte $94
        .byte $94
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $9A

        org $FFFC
        .word Start
        .word Start
