; Monet water + flowing lily sprite — internal/playfield.GenerateMonetSpriteASM
; per-scanline COLUBK(水) + per-scanline GRP0(睡蓮) をテーブルから。HMOVE で毎フレーム drift。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
NUSIZ0  = $04
COLUP0  = $06
COLUBK  = $09
RESP0   = $10
GRP0    = $1B
HMP0    = $20
HMOVE   = $2A

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #$C8
        sta COLUP0
        lda #$03
        sta NUSIZ0
        sta WSYNC
        ldx #12
DLY:    dex
        bne DLY
        sta RESP0
        lda #$F0
        sta HMP0

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        sta WSYNC
        sta HMOVE       ; 累積モーション適用（毎フレーム drift）
        ldx #36
VB:     sta WSYNC
        dex
        bne VB
        lda #0
        sta VBLANK

        ldy #0
VL:     sta WSYNC
        lda GRP0Tab,y   ; 睡蓮（HBLANK 内）
        sta GRP0
        lda BGTab,y     ; 水（HBLANK 内）
        sta COLUBK
        iny
        cpy #192
        bne VL
        lda #0
        sta GRP0

        lda #2
        sta VBLANK
        ldx #30
OS:     sta WSYNC
        dex
        bne OS
        jmp NextFrame

GRP0Tab
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $3C
        .byte $7E
        .byte $FF
        .byte $FF
        .byte $FF
        .byte $FF
        .byte $7E
        .byte $3C
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

BGTab
        .byte $78
        .byte $78
        .byte $78
        .byte $78
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $78
        .byte $78
        .byte $78
        .byte $78
        .byte $96
        .byte $96
        .byte $96
        .byte $96
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $8C
        .byte $8C
        .byte $8C
        .byte $8C
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $54
        .byte $54
        .byte $54
        .byte $54
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $6A
        .byte $B8
        .byte $B8
        .byte $B8
        .byte $B8
        .byte $BA
        .byte $BA
        .byte $BA
        .byte $BA
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $B4
        .byte $B4
        .byte $B4
        .byte $B4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C6
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $88
        .byte $88
        .byte $88
        .byte $88
        .byte $86
        .byte $86
        .byte $86
        .byte $86
        .byte $84
        .byte $84
        .byte $84
        .byte $84
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $8A
        .byte $96
        .byte $96
        .byte $96
        .byte $96
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $9C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $56
        .byte $56
        .byte $56
        .byte $56
        .byte $98
        .byte $98
        .byte $98
        .byte $98
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5A
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $5C
        .byte $64
        .byte $64
        .byte $64
        .byte $64
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $64
        .byte $64
        .byte $64
        .byte $64
        .byte $BC
        .byte $BC
        .byte $BC
        .byte $BC
        .byte $C8
        .byte $C8
        .byte $C8
        .byte $C8
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $B6
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $C4
        .byte $74
        .byte $74
        .byte $74
        .byte $74
        .byte $88
        .byte $88
        .byte $88
        .byte $88
        .byte $7A
        .byte $7A
        .byte $7A
        .byte $7A
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $7C
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $94
        .byte $94
        .byte $94
        .byte $94
        .byte $9A
        .byte $9A
        .byte $9A
        .byte $9A

        org $FFFC
        .word Start
        .word Start
