package vismatch

import (
	"fmt"
	"strings"
)

// PF register bit → visible-clock mapping for a 40-column playfield (hardware-
// verified, see docs/design-principles.md). Each PF column is 4 clocks wide.
//
//	LEFT half  clk 0..79 :  PF0 D4→0-3 D5→4-7 D6→8-11 D7→12-15 |
//	                        PF1 D7→16-19 … D0→44-47           | (MSB-first)
//	                        PF2 D0→48-51 … D7→76-79           | (LSB-first)
//	RIGHT half clk80..159 (repeat mode = independent right half, same bit order,
//	                        +80 clocks).
//
// pfHalf holds one half's three PF register bytes.
type pfHalf struct{ PF0, PF1, PF2 byte }

// encodeHalf sets, in a half's PF0/PF1/PF2, every 4px column whose left clock is
// lit. `lit(c)` reports whether the column starting at half-relative clock c
// (0,4,8,…76) is on. Bit order per the table above.
func encodeHalf(lit func(c int) bool) pfHalf {
	var h pfHalf
	// PF0: columns 0,4,8,12 → D4,D5,D6,D7
	for i, c := 0, 0; i < 4; i, c = i+1, c+4 {
		if lit(c) {
			h.PF0 |= 1 << (4 + i)
		}
	}
	// PF1: columns 16..44 → D7,D6,…,D0 (MSB first)
	for i, c := 0, 16; i < 8; i, c = i+1, c+4 {
		if lit(c) {
			h.PF1 |= 1 << (7 - i)
		}
	}
	// PF2: columns 48..76 → D0,D1,…,D7 (LSB first)
	for i, c := 0, 48; i < 8; i, c = i+1, c+4 {
		if lit(c) {
			h.PF2 |= 1 << i
		}
	}
	return h
}

// CactusBand is one measured vertical band of the target's playfield in the
// cactus columns, with the derived asm table bytes.
type CactusBand struct {
	ScanlineLo, ScanlineHi int
	ArenaLo, ArenaHi       int  // arena-line range = scanline - arenaTop
	CacL, CacR             byte // left-half PF2 (clk72-79) and right-half PF0 (clk80-95)
	Spans                  string
}

// MeasureCactus reads the target grid over [slLo,slHi] and derives, per band,
// the CacL (left-half PF2 covering clk72-79) and CacR (right-half PF0 covering
// clk80-95) bytes — exactly the asm's CacLTbl/CacRTbl entries — from which TIA
// object drew each pixel (PF vs not). arenaTop maps scanline→arena line. Bands
// are maximal runs of consecutive scanlines with identical (CacL,CacR).
func MeasureCactus(g *Grid, slLo, slHi, arenaTop int) []CactusBand {
	litPF := func(sl, clk int) bool {
		y := sl - g.Top
		if y < 0 || y >= g.H || clk < 0 || clk >= g.W {
			return false
		}
		return g.Elem[y][clk] == "PF"
	}
	var bands []CactusBand
	var cur *CactusBand
	for sl := slLo; sl <= slHi; sl++ {
		// left half PF2 uses clk 0..79; only 72-79 matter for the cactus.
		lh := encodeHalf(func(c int) bool { return litPF(sl, c) })
		// right half PF0 uses clk 80..159; column c (0..76) → absolute clk 80+c.
		rh := encodeHalf(func(c int) bool { return litPF(sl, 80+c) })
		cacL, cacR := lh.PF2, rh.PF0
		if cur != nil && cur.CacL == cacL && cur.CacR == cacR {
			cur.ScanlineHi = sl
			cur.ArenaHi = sl - arenaTop
			continue
		}
		if cur != nil {
			bands = append(bands, *cur)
		}
		cur = &CactusBand{ScanlineLo: sl, ScanlineHi: sl, ArenaLo: sl - arenaTop, ArenaHi: sl - arenaTop,
			CacL: cacL, CacR: cacR, Spans: elemSpans(g.Elem[sl-g.Top], "PF")}
	}
	if cur != nil {
		bands = append(bands, *cur)
	}
	return bands
}

// EmitCactusTables turns measured bands into paste-ready DASM: the CACxxx band
// constants and the CacLTbl / CacRTbl `ds N,$XX` run tables (indexed by arena
// line 0..tableLen-1; pre-cactus lines are $00). Only non-empty bands (CacL|CacR
// != 0) define the cactus extent; leading/trailing arena lines pad with $00.
func EmitCactusTables(bands []CactusBand, tableLen int) string {
	// Build per-arena-line CacL/CacR arrays, default 0.
	L := make([]byte, tableLen)
	R := make([]byte, tableLen)
	var top, bot int = -1, -1
	for _, b := range bands {
		if b.CacL == 0 && b.CacR == 0 {
			continue
		}
		if top < 0 {
			top = b.ArenaLo
		}
		bot = b.ArenaHi
		for a := b.ArenaLo; a <= b.ArenaHi && a < tableLen; a++ {
			if a < 0 {
				continue
			}
			L[a] = b.CacL
			R[a] = b.CacR
		}
	}
	var sb strings.Builder
	fmt.Fprintf(&sb, "; --- auto-generated by `vismatch -genpf` from the target ROM ---\n")
	fmt.Fprintf(&sb, "; cactus arena lines %d..%d (CACTOP..CACBOT-1); table length %d\n", top, bot, tableLen)
	// Constants from band boundaries (transitions in CacL or CacR).
	fmt.Fprintf(&sb, "CACTOP   = %d\n", top)
	fmt.Fprintf(&sb, "CACBOT   = %d\n", bot+1)
	sb.WriteString("CacLTbl:\n")
	sb.WriteString(emitRuns(L))
	sb.WriteString("CacRTbl:\n")
	sb.WriteString(emitRuns(R))
	return sb.String()
}

// emitRuns RLE-encodes a byte slice into `        ds N, $XX` lines.
func emitRuns(b []byte) string {
	var sb strings.Builder
	i := 0
	for i < len(b) {
		j := i
		for j < len(b) && b[j] == b[i] {
			j++
		}
		fmt.Fprintf(&sb, "        ds %d, $%02X              ; arena %d..%d\n", j-i, b[i], i, j-1)
		i = j
	}
	return sb.String()
}
