package vismatch

import (
	"path/filepath"
	"testing"

	"github.com/kidsnz/atari2600-harness/internal/build"
)

// MeasurePF decides whether a target's playfield is repeat, reflect or asymmetric,
// and the caller emits tables from that decision — dropping the right half when it
// says repeat or reflect. A wrong decision there silently loses half the picture.
//
// The existing TestGeneratedPFMatchesTIARegisters checks the generated BYTES, but
// only on ROMs this same function classified as repeat or reflect: it grades the
// decision using the decision. This grades it against the PIXELS instead — if the
// mode says repeat, the right half of every covered line must equal the left, read
// straight off the attribution grid.
//
// It also prints its own denominator, because the first version of this test
// reported "31 of 31 sound" while 24 of those ROMs draw NO PLAYFIELD AT ALL, where
// "left half off equals right half off" is true by default. A pass over nothing is
// the failure mode this repo keeps finding in its own tools.
func TestPFModeDecisionAgreesWithThePixels(t *testing.T) {
	files, err := filepath.Glob("../../roms/techniques/*.asm")
	if err != nil || len(files) == 0 {
		t.Skip("technique corpus unavailable")
	}
	graded, vacuous, totalSamples := 0, 0, 0
	for _, asm := range files {
		bin := build.BinPathFor(asm)
		if out, err := build.Assemble(asm, bin); err != nil {
			t.Logf("assemble %s: %s", asm, out)
			continue
		}
		g, err := ExtractROM(bin, "NTSC", 4, false)
		if err != nil || g == nil || g.H == 0 {
			continue
		}
		bands, mode := MeasurePF(g, g.Top, g.Top+g.H-1)
		if len(bands) == 0 {
			continue
		}

		lit, disagree := 0, 0
		for _, b := range bands {
			for sl := b.ScanlineLo; sl <= b.ScanlineHi; sl++ {
				y := sl - g.Top
				if y < 0 || y >= len(g.Elem) {
					continue
				}
				row := g.Elem[y]
				for c := 0; c < 20; c++ {
					left := row[4*c] == "PF"
					same := row[80+4*c] == "PF"       // repeat: same column, right half
					mirr := row[80+4*(19-c)] == "PF"  // reflect: mirrored column
					if left || same || mirr {
						lit++
					}
					switch mode {
					case PFRepeat:
						if left != same {
							disagree++
						}
					case PFReflect:
						if left != mirr {
							disagree++
						}
					}
				}
			}
		}

		if lit == 0 {
			// No playfield anywhere: the comparison is true by default and grades
			// nothing. Counted, not quietly folded into a pass.
			vacuous++
			continue
		}
		graded++
		totalSamples += lit
		if disagree > 0 {
			t.Errorf("%s: mode %q but %d of %d lit column samples disagree between the halves — the "+
				"emitted tables drop the right half in this mode, so that much of the picture is lost",
				filepath.Base(asm), mode, disagree, lit)
		}
	}

	if graded == 0 {
		t.Fatal("no ROM with an actual playfield was graded, so this test proves nothing")
	}
	t.Logf("PF mode decision agreed with the pixels on %d ROMs over %d lit column samples; "+
		"%d ROMs draw no playfield at all and are NOT covered by that claim", graded, totalSamples, vacuous)
	if vacuous < 20 {
		t.Logf("note: only %d ROMs were vacuous; the corpus has gained playfield coverage since this "+
			"test was written (it was 24 of 31)", vacuous)
	}
}
