#!/usr/bin/env python3
"""check_provenance.py — harness の全要素が「原典」を記録しているか検査する（CI/手元 lint）。

ルール（[[feedback-provenance-always]]）：harness に入れる全要素は、どの原典から来たかを必ず
出典として記録する。実制作で不具合時に**オリジナルソースへ戻って調べ直せる**ようにするため。

検査対象と合格条件（いずれかの provenance マーカーを含めば合格）:
  - docs/techniques/<name>.md（README/roadmap 除く）：外部参照（Source/Learned from/topic/<id>/
    8bitworkshop/Spice/Davie 等）or 自前の検証根拠（litmus_*/Hardware basis/Foundation）。
  - pkg/design/<name>.go（_test 除く）：採掘番号 / design-principles 参照 / 〔出典〕コメント。
  - docs/design-principles.md：〔...〕出典タグが一定数以上。

使い方:
    cd harness && python3 scripts/check_provenance.py        # 全件検査（欠落あれば exit 1）
    cd harness && python3 scripts/check_provenance.py --list  # docs/provenance.md を再生成（要素→原典の一覧）
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HARNESS = os.path.normpath(os.path.join(HERE, ".."))

# provenance とみなすマーカー（大文字小文字無視）。外部参照 or 自前検証根拠 or 引用括弧。
MARKERS = re.compile(
    r"source:|出典|learned from|reference:|based on|derived from|〔|"
    r"litmus_|hardware basis|hardware-verified|foundation:|"
    r"reference/|topic/\d|8bitworkshop|spice|davie|staugas|whitehead|hugg",
    re.IGNORECASE,
)

SKIP_DOCS = {"README.md", "roadmap.md", "roadmap.ja.md", "README.ja.md"}


def techniques_docs():
    d = os.path.join(HARNESS, "docs", "techniques")
    for fn in sorted(os.listdir(d)):
        # 公開正本（英語 .md）のみ検査。*.ja.md は gitignore のローカル翻訳＝対象外。
        if fn.endswith(".md") and not fn.endswith(".ja.md") and fn not in SKIP_DOCS:
            yield os.path.join(d, fn)


def pkg_design_files():
    d = os.path.join(HARNESS, "pkg", "design")
    for fn in sorted(os.listdir(d)):
        if fn.endswith(".go") and not fn.endswith("_test.go"):
            yield os.path.join(d, fn)


def has_marker(path):
    try:
        with open(path, encoding="utf-8") as f:
            return bool(MARKERS.search(f.read()))
    except OSError:
        return False


def rel(p):
    return os.path.relpath(p, HARNESS)


def first_marker_line(path):
    """provenance を述べている最初の行を返す（一覧用の短い出典文）。"""
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                if MARKERS.search(line):
                    return line.strip().lstrip("# ").strip()
    except OSError:
        pass
    return ""


def write_list():
    """docs/provenance.md＝要素→原典の集約一覧（手書きせず自動生成・最悪時の戻り先索引）。"""
    out = ["# Provenance map — every harness element → its origin\n",
           "Auto-generated by `scripts/check_provenance.py --list`. A low-traffic reference: open it only\n"
           "when something built on a technique/rule misbehaves and you need to go back to the original source.\n",
           "Recording is the strict part (CI-enforced); this list is just the consolidated lookup.\n",
           "\n## Techniques (`docs/techniques/<name>.md` → source)\n",
           "| technique | recorded source |\n|---|---|\n"]
    for p in techniques_docs():
        out.append("| `%s` | %s |\n" % (os.path.basename(p), first_marker_line(p) or "—"))
    out.append("\n## Other provenance layers\n")
    out.append("- **Design rules** → `docs/design-principles.md` (each rule ends with `〔source〕`).\n")
    out.append("- **`pkg/design` functions** → source comment in each `pkg/design/*.go`.\n")
    out.append("- **Mined AtariAge threads** → `docs/mining-digest.md` (topic_id + URL → what it feeds).\n")
    out.append("- **Raw per-thread notes** → `reference/atariage/<id>-*/notes.ja.md` (provenance, not committed).\n")
    open(os.path.join(HARNESS, "docs", "provenance.md"), "w", encoding="utf-8").write("".join(out))
    print("wrote docs/provenance.md")


def main():
    if "--list" in sys.argv:
        write_list()
        return
    missing = []
    for p in techniques_docs():
        if not has_marker(p):
            missing.append(rel(p))
    for p in pkg_design_files():
        if not has_marker(p):
            missing.append(rel(p))

    # design-principles は出典タグ数で粗くチェック。
    dp = os.path.join(HARNESS, "docs", "design-principles.md")
    if os.path.isfile(dp):
        with open(dp, encoding="utf-8") as f:
            tags = f.read().count("〔")
        if tags < 20:
            missing.append("docs/design-principles.md (citations 〔〕=%d, want >=20)" % tags)

    if missing:
        print("PROVENANCE MISSING — these need a source/出典/litmus citation:")
        for m in missing:
            print("  ✗", m)
        print("\nrule: [[feedback-provenance-always]] — every harness element records its origin.")
        sys.exit(1)
    print("provenance OK — all technique docs / pkg/design / design-principles cite their source.")


if __name__ == "__main__":
    main()
