#!/usr/bin/env python3
"""Generate `roms/litmus/litmus_resmp_width.asm` — does the RESMP offset scale with width?

`litmus_resmp.asm` + `roms/litmus/scenarios/resmp.json` already measure the offset and
lock it at +4: player0.hmoved_pixel 24, missile0.hmoved_pixel 28. That fixture sweeps the
player with HMOVE and confirms the missile follows, but it uses **one player width**.

This one asks the question that width leaves open. `docs/fundamentals-audit.md:53` says
"release leaves M centered on P" — and centred is a claim about width, so it can only be
checked by changing the width.

"Centred" is the interesting part: a player is 8 colour clocks wide at NUSIZ 1x, 16 at
2x and 32 at 4x, so if the missile really lands at the centre the offset must scale with
the width. If it is a fixed +4 it does not. One fixture answers both, and the answer
changes what a bullet-spawn routine has to do when the shooter is a double-width sprite.

Shape: one band per (player width, player position). The band strobes RESP0 at a known
cycle, locks the missile with RESMP0 = D1, then releases it, and draws the player and the
missile on SEPARATE lines - they share COLUP0, so a line carrying both cannot be read
apart by colour.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "roms", "litmus", "litmus_resmp_width.asm")
BIN = os.path.join(ROOT, "roms", "litmus", "litmus_resmp_width.bin")

# NUSIZ0 low three bits: 0 = one copy 1x, 5 = one copy 2x wide, 7 = one copy 4x wide.
WIDTHS = [(0x00, "1x", 8), (0x05, "2x", 16), (0x07, "4x", 32)]
# Extra `dec scratch` (5 cy each) before the RESP0 strobe: moves the player 15 clocks.
POSITIONS = [0, 1, 2, 3]
BAND = 7          # setup, strobe+lock, draw-while-locked, release+player, missile, spare
BASE_DECS = 3
VISIBLE = 192

bands = [(w, n, wide, p) for (w, n, wide) in WIDTHS for p in POSITIONS]
used = len(bands) * BAND
assert used <= VISIBLE, (used, VISIBLE)

L = []
w = L.append
w("; litmus_resmp — where RESMP leaves the missile when the lock is released")
w(";   (GENERATED by scripts/gen_litmus_resmp.py — edit that, not this file)")
w(";")
w("; Closes docs/fundamentals-audit.md:53, which says 'release leaves M centered on P")
w("; (Stella PG). ⬜ exact lock offset' — the ⬜ is harness saying it does not know the")
w("; number, while roms/techniques/bullets.asm:3 states +4px. Neither was graded.")
w(";")
w("; The player is drawn on one line and the missile on the next, because they share")
w("; COLUP0 and a line carrying both cannot be read apart by colour.")
w(";")
w("; %d bands x %d lines = %d picture lines, %d blank." % (len(bands), BAND, used, VISIBLE - used))
w("        processor 6502")
w("VSYNC   = $00")
w("VBLANK  = $01")
w("WSYNC   = $02")
w("NUSIZ0  = $04")
w("COLUP0  = $06")
w("COLUBK  = $09")
w("RESP0   = $10")
w("GRP0    = $1B")
w("ENAM0   = $1D")
w("HMCLR   = $2B")
w("RESMP0  = $28")
w("scratch = $82")
w("")
w("        org $F000")
w("Start:")
w("        sei")
w("        cld")
w("        ldx #$FF")
w("        txs")
w("        lda #0")
w("Clr:    sta $00,x")
w("        dex")
w("        bne Clr")
w("        sta HMCLR")
w("        lda #$0E")
w("        sta COLUP0")
w("")
w("NextFrame:")
w("        lda #2")
w("        sta VSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        lda #0")
w("        sta VSYNC")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #37")
w("VB:     sta WSYNC")
w("        dex")
w("        bne VB")
w("        lda #0")
w("        sta VBLANK")
w("")
for nus, name, wide, pos in bands:
    w("        ; --- NUSIZ0=%s (%s, %d clocks), position +%d ---" % (hex(nus), name, wide, pos))
    w("        sta WSYNC")
    w("        lda #$%02X" % nus)
    w("        sta NUSIZ0")
    w("        lda #0")
    w("        sta GRP0")
    w("        sta ENAM0")
    w("        ; --- strobe RESP0, then lock the missile to the player ---")
    w("        sta WSYNC")
    for _ in range(BASE_DECS + pos):
        w("        dec scratch         ; 5 cy")
    w("        sta RESP0")
    w("        lda #2")
    w("        sta RESMP0          ; D1 = lock M0 to P0")
    w("        ; --- the lock has to be HELD for a full scanline. The snap fires when the")
    w("        ;     player's scan counter reaches a particular pixel (Gopher2600")
    w("        ;     player.go:776 triggerMissileReset: pixel 2 at 1x, pixel 4 count 1 at 2x,")
    w("        ;     pixel 5 count 3 at 4x), which only comes round once the position counter")
    w("        ;     has walked the line. A band that locks and releases inside the same line")
    w("        ;     never snaps: the first version of this fixture did that and read a")
    w("        ;     constant 17 in every band.")
    w("        ;     NOTE: it is the HOLD that matters, not the drawing. This comment first")
    w("        ;     said the player had to be drawn; removing the graphics byte and keeping")
    w("        ;     the held line leaves every measurement unchanged, while keeping the")
    w("        ;     graphics and dropping the held line breaks three of the four gradings.")
    w("        sta WSYNC")
    w("        lda #$FF")
    w("        sta GRP0            ; full bar: the scan counter runs the whole width")
    w("        sta WSYNC           ; one full line of drawing = the snap")
    w("        ; --- release; the missile keeps where the lock left it ---")
    w("        lda #0")
    w("        sta RESMP0")
    w("        ; --- player alone (one pixel, so its left edge is unambiguous) ---")
    w("        sta WSYNC")
    w("        lda #$80")
    w("        sta GRP0")
    w("        ; --- missile alone: they share COLUP0, so they cannot share a line ---")
    w("        sta WSYNC")
    w("        lda #0")
    w("        sta GRP0")
    w("        lda #2")
    w("        sta ENAM0")
    w("        sta WSYNC")
    w("        lda #0")
    w("        sta ENAM0")
if VISIBLE - used > 0:
    w("        ldx #%d" % (VISIBLE - used))
    w("Fill:   sta WSYNC")
    w("        dex")
    w("        bne Fill")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #30")
w("OS:     sta WSYNC")
w("        dex")
w("        bne OS")
w("        jmp NextFrame")
w("")
w("        org $FFFC")
w("        .word Start")
w("        .word Start")

open(ASM, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", ASM, "-f3", "-o" + BIN], check=True)
print("%d bands (%d widths x %d positions), %d picture lines, %d blank"
      % (len(bands), len(WIDTHS), len(POSITIONS), used, VISIBLE - used))
