#!/usr/bin/env python3
"""Generate roms/litmus/litmus_sprite_place.asm.

The fixture is generated rather than hand-written because every band turns on a strobe or a write
landing on an EXACT cycle, and the padding that gets it there is arithmetic, not judgement. Run
this after changing a band; the .asm is committed, the .bin is not (CI assembles it).

    python3 scripts/gen_litmus_sprite_place.py

Graded by internal/emu/spriteplace_test.go, written up in docs/techniques/sprite-placement.md.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), 'roms', 'litmus', 'litmus_sprite_place.asm')
BAND = 4                      # every band is four scanlines, so the grader can index them


def pad(n, why=""):
    if n < 0 or n == 1:
        raise SystemExit("cannot pad %d cycles (%s)" % (n, why))
    out = []
    if n % 2:
        out.append(("        bit $80         ; 3", 3)); n -= 3
    return out + [("        nop             ; 2", 2)] * (n // 2)


L = []
A = L.append


def emit(lines_and_costs, cy):
    for txt, n in lines_and_costs:
        A(txt); cy += n
    return cy


def strobe(reg, want, cy, note=""):
    """pad to put `reg`'s WRITE on cycle `want`, then strobe."""
    cy = emit(pad((want - 2) - cy, "%s at %d" % (reg, want)), cy)
    A("        sta %-8s   ; write cycle %d%s" % (reg, want, note))
    return cy + 3


A("; litmus_sprite_place — where RESP and RESM put an object, when a write reaches the copy it is")
A("; meant for, and what a strobe does NOT do on the line it runs on.")
A(";")
A("; GENERATED by scripts/gen_litmus_sprite_place.py — every band lands a strobe or a write on an")
A("; exact cycle and the padding that gets it there is arithmetic. Edit the generator, not this.")
A(";")
A("; These are the numbers a kernel author needs BEFORE deciding whether a shape wider than eight")
A("; pixels can be drawn at all. None of them was written down anywhere in this repository until")
A("; 2026-08-21; they were re-derived from throwaway probes twice in one session.")
A(";")
A(";   1. a RESP strobe whose WRITE cycle is c puts a NORMAL-width player at x = 3c - 60")
A(";   2. a RESM strobe puts a missile at x = 3c - 61 — one clock further LEFT from the same cycle")
A(";   3. so RESM three cycles after RESP puts the missile at EXACTLY player + 8, which is where an")
A(";      8 px player stops drawing. Two RESP strobes never can: three cycles is the shortest gap")
A(";      between two stores and three cycles is nine colour clocks.")
A(";   4. a missile follows its player's NUSIZ copies")
A(";   5. a strobe does not draw the new position on the line it runs on")
A(";   6. a GRP write takes effect at screen x = 3w - 64, so it needs FOUR colour clocks of margin")
A(";      ahead of the copy it feeds and not one more")
A(";   7. a normal-width player cannot be strobed left of x=3")
A(";   9. a missile and the ball are clamped at x=2 and a player at x=3, and each clamp spans a")
A(";      WINDOW of write cycles, not one")
A(";  10. a NUSIZ copy past 160 wraps to the left edge and draws there on the same line")
A(";   8. and a strobe cancels the pending draw of the FIRST copy ONLY — the copies NUSIZ makes at")
A(";      +32 and +64 are triggered from the reset position and still land on the strobe line")
A(";")
A("; LAYOUT. Eleven bands of four scanlines each. Band b's lines are 4b..4b+3, counting from the")
A("; first band's line 0; the grader finds that line and indexes from it.")
A(";")
A(";   band  line  what it shows")
A(";    0     1-3  RESP0 write cycle 24            -> P0 at 12")
A(";    1     1-3  RESP0 write cycle 40            -> P0 at 60")
A(";    2     1-3  RESM0 write cycle 24            -> M0 at 11")
A(";    3     1-3  RESM0 write cycle 40            -> M0 at 59")
A(";    4     1-3  RESP0 at 30 then RESM0 at 33    -> P0 30..37 and M0 38..41, abutting")
A(";    5     1-3  the same with NUSIZ0 = $26      -> three of those, 32 px apart")
A(";    6     1-3  P0 lit across its own RESP0     -> old position on the strobe line, new one after")
A(";    7     1-3  GRP0 <- 0 on cycle 43 / 42 / 41 -> copy 1 keeps 3 px / is clean / is clean")
A(";    8     1,3  RESP0 write cycle 17 and 21     -> both land on x=3, the clamp")
A(";    9     1,3  RESP0 write cycle 22 and 25     -> x=6 and x=15, the formula above the clamp")
A(";   10     2,3  a mid-line strobe               -> copy 0 gone, copies 1 and 2 drawn anyway")
A(";   11     1,3  RESM0 write cycle 17 and 21     -> both land on x=2, the missile's clamp")
A(";   12     1,3  RESM0 write cycle 22 and 25     -> x=5 and x=14, the formula above the clamp")
A(";   13     1,3  RESBL write cycle 24 and 40     -> x=11 and x=59: the ball IS a missile grid")
A(";   14     1,3  RESBL write cycle 17 and 21     -> both land on x=2, the ball's clamp")
A(";   15     1-3  P0 at x=120 with three copies   -> 120, 152 and a WRAPPED one at 24")
A("")
A("        processor 6502")
A("VSYNC   = $00")
A("VBLANK  = $01")
A("WSYNC   = $02")
A("NUSIZ0  = $04")
A("COLUP0  = $06")
A("COLUBK  = $09")
A("RESP0   = $10")
A("RESM0   = $12")
A("GRP0    = $1B")
A("ENAM0   = $1D")
A("RESBL   = $14")
A("ENABL   = $1F")
A("CTRLPF  = $0A")
A("COLUPF  = $08")
A("HMCLR   = $2B")
A("")
A("        org $F000")
A("Reset:")
A("        sei")
A("        cld")
A("        ldx #0")
A("        txa")
A("Clr:    dex")
A("        txs")
A("        pha")
A("        bne Clr")
A("        sta HMCLR       ; nothing here ever strobes HMOVE — every position is RESP/RESM alone")
A("        lda #$00")
A("        sta COLUBK")
A("        lda #$0E")
A("        sta COLUP0")
A("        sta COLUPF      ; the ball draws in COLUPF, and bands 13-14 need to see it")
A("        lda #$20")
A("        sta CTRLPF      ; ball 4 px wide")
A("")
A("Frame:")
A("        lda #2")
A("        sta VSYNC")
A("        sta WSYNC")
A("        sta WSYNC")
A("        sta WSYNC")
A("        lda #0")
A("        sta VSYNC")
A("        ldx #37")
A("Vb:     sta WSYNC")
A("        dex")
A("        bne Vb")
A("        lda #0")
A("        sta VBLANK")

lines = 0


def newline():
    global lines
    A("        sta WSYNC")
    lines += 1
    return 0


def show(grp=None, enam=None, enabl=None):
    """a display line: put the graphics up in HBLANK and let the objects draw"""
    cy = newline()
    if grp is not None:
        A("        lda #$%02X" % grp); A("        sta GRP0"); cy += 5
    if enam is not None:
        A("        lda #$%02X" % enam); A("        sta ENAM0"); cy += 5
    if enabl is not None:
        A("        lda #$%02X" % enabl); A("        sta ENABL"); cy += 5
    return cy


def band_positions(n, note, nusiz, strobes, grp, enam):
    """bands 0..5: a setup line that draws nothing, then three lines that show the result"""
    A("")
    A("; ---- band %d: %s ----" % (n, note))
    cy = newline()
    A("        lda #0          ; 2   the setup line draws nothing, so it cannot be mistaken")
    A("        sta GRP0        ; 3   for the result")
    A("        sta ENAM0       ; 3")
    A("        lda #$%02X        ; 2" % nusiz)
    A("        sta NUSIZ0      ; 3")
    cy = 13
    for reg, want in strobes:
        cy = strobe(reg, want, cy)
    for _ in range(3):
        show(grp, enam)


band_positions(0, "RESP0 write cycle 24 -> P0 at 12", 0x00, [("RESP0", 24)], 0x80, 0x00)
band_positions(1, "RESP0 write cycle 40 -> P0 at 60", 0x00, [("RESP0", 40)], 0x80, 0x00)
band_positions(2, "RESM0 write cycle 24 -> M0 at 11", 0x00, [("RESM0", 24)], 0x00, 0x02)
band_positions(3, "RESM0 write cycle 40 -> M0 at 59", 0x00, [("RESM0", 40)], 0x00, 0x02)
band_positions(4, "RESP0 at 30 then RESM0 at 33 -> P0 30..37 + M0 38..41", 0x20,
               [("RESP0", 30), ("RESM0", 33)], 0xFF, 0x02)
band_positions(5, "the same, NUSIZ0=$26: three copies 32 apart", 0x26,
               [("RESP0", 30), ("RESM0", 33)], 0xFF, 0x02)

A("")
A("; ---- band 6: a strobe does not draw the NEW position on its own line ----")
cy = newline()
A("        lda #0")
A("        sta ENAM0")
A("        sta NUSIZ0      ; back to one copy, no missile")
A("        lda #$80")
A("        sta GRP0        ; P0 is LIT for all of this band, at x=30 left over from band 5")
show()                                   # line 1: the old position
cy = newline()                           # line 2: the strobe line — still the old position
cy = strobe("RESP0", 40, cy, "  -> x=60, but NOT on this line")
show()                                   # line 3: the new position at last

A("")
A("; ---- band 7: how late a GRP write can be and still reach its copy ----")
A("; P0 sits at x=30 with three copies, at 30, 62 and 94. Each line below puts GRP0 up as $FF in")
A("; HBLANK and drops it to $00 partway across. Copy 0 has already drawn; whether copy 1 at x=62")
A("; comes out clean says whether the write reached it. 3w-68 steps by three, so 43, 42 and 41")
A("; land the write at x=61, 58 and 55 — one, four and seven clocks ahead of copy 1.")
cy = newline()
A("        lda #$06")
A("        sta NUSIZ0")
A("        lda #0")
A("        sta GRP0")
A("        sta ENAM0")
cy = 13
cy = strobe("RESP0", 30, cy, "  -> x=30, copies at 30/62/94")
for w in (43, 42, 41):
    cy = newline()
    A("        lda #$FF")
    A("        sta GRP0        ; up in HBLANK, so copy 0 at x=30 always draws")
    cy = 5
    cy = emit(pad((w - 4) - cy, "GRP0<-0 at %d" % w), cy)
    A("        lda #0")
    A("        sta GRP0        ; write cycle %d, lands at x=%d, %d clocks before copy 1"
      % (w, 3 * w - 68, 62 - (3 * w - 68)))

A("")
A("; ---- band 8: a normal-width player cannot be strobed left of x=3 ----")
for want in (17, 21):
    cy = newline()
    A("        lda #$00")
    A("        sta NUSIZ0      ; one copy, normal width")
    A("        lda #0")
    A("        sta GRP0")
    cy = 10
    cy = strobe("RESP0", want, cy, "  -> the clamp, not 3c-60")
    show(0x80)

A("")
A("; ---- band 9: and above the clamp the formula holds ----")
for want, x in ((22, 6), (25, 15)):
    cy = newline()
    A("        lda #0")
    A("        sta GRP0")
    cy = 5
    cy = strobe("RESP0", want, cy, "  -> x=%d = 3*%d - 60" % (x, want))
    show(0x80)

A("")
A("; ---- band 10: a strobe cancels the FIRST copy only ----")
A("; P0 is lit and parked at x=42 with three copies, at 42, 74 and 106. The third line strobes it")
A("; to x=24 while the beam is at 16 — ahead of every one of those. If a strobe simply moved the")
A("; object, x=24 would draw; if it cancelled the object, nothing would. What happens is neither:")
A("; copy 0 is gone and the copies at 24+32 and 24+64 land anyway, because they are triggered from")
A("; the reset position and the counter reaches them before the line ends.")
cy = newline()
A("        lda #$06")
A("        sta NUSIZ0")
A("        lda #0")
A("        sta GRP0")
A("        sta ENAM0")
cy = 13
cy = strobe("RESP0", 34, cy, "  -> x=42, copies at 42/74/106")
show(0x80)                               # line 1: 42, 74, 106
cy = newline()                           # line 2: the strobe line
cy = strobe("RESP0", 28, cy, "  -> x=24 while the beam is at 16")
show()                                   # line 3: 24, 56, 88

A("")
A("; ---- band 11: a missile is clamped at x=2, and the clamp is a WINDOW of write cycles ----")
A("; Band 8 showed a player clamped at 3. A missile stops one clock further LEFT, at 2 — a place no")
A("; player can be reached to by any strobe or any copy of one. Both cycles below land on it, and")
A("; that the clamp spans SEVERAL cycles rather than one is the load-bearing part: it is what lets")
A("; an object at the wall be strobed clear of another four pixels to its right, which anywhere")
A("; else on the grid would be one cycle away and therefore impossible for two 3-cycle stores.")
for want in (17, 21):
    cy = newline()
    A("        lda #$00")
    A("        sta NUSIZ0      ; one copy, missile 1 px")
    A("        lda #0")
    A("        sta GRP0")
    A("        sta ENAM0")
    cy = 13
    cy = strobe("RESM0", want, cy, "  -> the clamp at x=2, not 3c-61")
    show(None, 0x02)

A("")
A("; ---- band 12: and above its clamp the missile formula holds ----")
for want, x in ((22, 5), (25, 14)):
    cy = newline()
    A("        lda #0")
    A("        sta ENAM0")
    cy = 5
    cy = strobe("RESM0", want, cy, "  -> x=%d = 3*%d - 61" % (x, want))
    show(None, 0x02)

A("")
A("; ---- band 13: the BALL places exactly like a missile ----")
A("; The fifth movable object, and the one this catalogue had never measured. RESBL obeys the same")
A("; x = 3c - 61 as RESM, so the ball shares the missile's grid -- one clock left of the player's --")
A("; and can stand in for a missile wherever a row has run out of them.")
for want, x in ((24, 11), (40, 59)):
    cy = newline()
    A("        lda #0")
    A("        sta ENABL")
    A("        sta ENAM0       ; band 12's missile off, so only the ball is in this band")
    cy = 8
    cy = strobe("RESBL", want, cy, "  -> x=%d = 3*%d - 61, same as RESM" % (x, want))
    show(None, None, 0x02)

A("")
A("; ---- band 14: and the ball is clamped at x=2, like a missile and unlike a player ----")
for want in (17, 21):
    cy = newline()
    A("        lda #0")
    A("        sta ENABL")
    A("        sta ENAM0")
    cy = 8
    cy = strobe("RESBL", want, cy, "  -> the clamp at x=2")
    show(None, None, 0x02)

A("")
A("; ---- band 15: a NUSIZ copy past 160 WRAPS and draws at the left edge, on the same line ----")
A("; P0 is strobed to x=120 with three copies, which NUSIZ puts at 120, 152 and 184. There is no")
A("; 184 on a 160-clock line: the position counter folds it to 24 and the copy draws THERE, on the")
A("; same scanline, with whatever GRP0 held when the beam passed. So an object strobed on the right")
A("; of the screen can put a copy on the far left -- including at positions no strobe can reach.")
cy = newline()
A("        lda #0")
A("        sta ENABL")
A("        sta ENAM0")
A("        lda #$06")
A("        sta NUSIZ0      ; three copies, 32 apart")
cy = 13
cy = strobe("RESP0", 60, cy, "  -> x=120; copies at 120, 152 and 184->24")
show(0x80)
show(0x80)
show(0x80)

newline()                                # a spare line: the cleanup below must not run on line 3

A("")
A("        lda #0")
A("        sta GRP0")
A("        sta ENAM0")
A("        ldx #%d" % (192 - lines))
A("Rest:   sta WSYNC")
A("        dex")
A("        bne Rest")
A("        lda #2")
A("        sta VBLANK")
A("        ldx #30")
A("Os:     sta WSYNC")
A("        dex")
A("        bne Os")
A("        jmp Frame")
A("")
A("        org $FFFC")
A("        word Reset")
A("        word Reset")

open(OUT, 'w').write('\n'.join(L) + '\n')
print("%s: %d visible scanlines used, %d bands of %d" % (OUT, lines, lines // BAND, BAND))
