#!/usr/bin/env python3
"""Build roms/litmus/litmus_restrobe.asm/.bin — what a mid-line RESP strobe is worth.

Graded by internal/emu/restrobe_test.go; the rules are in docs/techniques/restrobe-copies.md.

WHY THIS FIXTURE GREW. Its first version measured ONE strobe spacing, eight cycles, and the doc
generalised from it twice — "any spacing at or above three cycles works" and "an added copy is
never at x = 0 (mod 3) ... two consequences bind every kernel". Sweeping the spacing showed both
are false: at three and five cycles the ladder is FLAT, at twelve it climbs faster than 3+k, and at
six every added copy lands ON the multiple-of-three grid. A ladder measured at one spacing cannot
tell a law from a coincidence, which is the rule check_instruments.py enforces for instruments and
this fixture was not obeying for itself.

WHAT IS ON SCREEN. P0 is parked at x=3 with NUSIZ=3 (three copies, sixteen apart) while the screen
is still blank. Then, for every (spacing, k) the machine can actually build:

    line 0   re-park: RESP0 back to x=3. The strobe is in blank, so this line still shows where
             the PREVIOUS band left the player -- it is not a baseline and must not be read as one
    line 1   untouched. The parked three at 3, 19, 35. THIS is the sentinel the grader walks by,
             so that no band is ever identified by a hard-coded scanline number
    line 2   the measurement: k re-strobes, `spacing` cycles apart, first one at cycle 29

A final band puts BOTH players in copy mode and interleaves their strobes, because the doc's
opening sentence claims two players reach sixteen slots and only one player had ever been measured.

The order of BANDS below is part of the contract with the grader: it walks sentinels and pairs the
line after each with this list, in this order. Change one and the other fails loudly.
"""
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

PARK_CYCLE = 21          # the RESP0 WRITE cycle that parks the player at its leftmost, x=3
FIRST = 29               # the first re-strobe of every band, so spacing is the only variable
SPACINGS = (3, 4, 5, 6, 7, 8, 10, 12)
KMAX = 5
LAST_CYCLE = 74          # a strobe whose store ends later than this runs out of scanline

# The two-player band. P1 parks two cycles behind P0 -- 24 is the next cycle a three-cycle store
# can END on after 21, so x = 3*24 - 60 = 12; 23 is not a position this machine can reach.
P1_PARK_CYCLE = 24
TWO_STEP = 6             # the spacing that packs the two players tightest without a 1-cycle gap
TWO_K = 5


def pad(n):
    """n cycles of nothing. nop is 2 and bit on zero page is 3, so one cycle cannot be built."""
    if n < 0 or n == 1:
        raise SystemExit("pad %d cannot be built" % n)
    out = []
    if n % 2:
        out.append("        bit $80")
        n -= 3
    return out + ["        nop"] * (n // 2)


def buildable(cycles):
    """Can these store-end cycles be reached in order? A gap of exactly one cannot be filled."""
    cy = 0
    for c in cycles:
        gap = c - 2 - cy
        if gap < 0 or gap == 1:
            return False
        cy = c + 1
    return c <= LAST_CYCLE


def strobes(cycles, reg="RESP0"):
    out, cy = [], 0
    for c in cycles:
        out += pad(c - 2 - cy)
        out.append("        sta %-6s          ; write cycle %d -> base x=%d" % (reg, c, 3 * c - 60))
        cy = c + 1
    return out


BANDS = []
for s in SPACINGS:
    for k in range(1, KMAX + 1):
        cs = [FIRST + i * s for i in range(k)]
        if buildable(cs):
            BANDS.append(("s%d k%d" % (s, k), cs))

L = ["; litmus_restrobe.asm — GENERATED by scripts/gen_litmus_restrobe.py. Do not hand-edit.",
     "; Bands of three lines: re-park, an untouched sentinel showing the parked three, then the",
     "; measurement. The strobe SPACING is swept, because the ladder is not the same at every one.",
     "        processor 6502",
     "VSYNC = $00", "VBLANK = $01", "WSYNC = $02", "NUSIZ0 = $04", "NUSIZ1 = $05",
     "COLUP0 = $06", "COLUP1 = $07", "COLUBK = $09", "GRP0 = $1B", "GRP1 = $1C",
     "RESP0 = $10", "RESP1 = $11",
     "        org $F000",
     "Reset:  sei", "        cld", "        ldx #0", "        txa",
     "Clear:  dex", "        txs", "        pha", "        bne Clear",
     "        lda #$00", "        sta COLUBK",
     "        lda #$0E", "        sta COLUP0",
     "        lda #$44", "        sta COLUP1        ; a different colour, so the two can be told apart",
     "        lda #$03", "        sta NUSIZ0        ; three copies, sixteen apart",
     "        sta NUSIZ1",
     "Frame:  lda #2", "        sta VSYNC",
     "        sta WSYNC", "        sta WSYNC", "        sta WSYNC",
     "        lda #0", "        sta VSYNC",
     "        ldx #35", "VbPad:  sta WSYNC", "        dex", "        bne VbPad",
     "        sta WSYNC"] + pad(PARK_CYCLE - 2) + [
     "        sta RESP0         ; write cycle %d -> x = 3c-60 = 3, the leftmost a player reaches"
     % PARK_CYCLE,
     "        lda #0", "        sta VBLANK",
     "        lda #$FF", "        sta GRP0",
     "        lda #$00", "        sta GRP1          ; P1 stays dark until the two-player band"]

lines = 0
for tag, cs in BANDS:
    L.append("; ---- band %s: %d re-strobe(s) at cycles %s ----" % (tag, len(cs), cs))
    L.append("        sta WSYNC")
    L += pad(PARK_CYCLE - 2) + ["        sta RESP0         ; re-park to x=3"]
    lines += 1
    L.append("        sta WSYNC         ; sentinel: untouched, the parked three at 3, 19, 35")
    lines += 1
    L.append("        sta WSYNC")
    L += strobes(cs)
    lines += 1

# ---- the two-player band. Its sentinel is the same shape, so the grader walks it identically.
p0 = [FIRST + i * TWO_STEP for i in range(TWO_K)]
p1 = [c + 3 for c in p0]
both = sorted([(c, "RESP0") for c in p0] + [(c, "RESP1") for c in p1])
if not buildable([c for c, _ in both]):
    raise SystemExit("the two-player schedule cannot be built")
L.append("; ---- band two-players: P0 %s / P1 %s ----" % (p0, p1))
L.append("        sta WSYNC")
L += pad(PARK_CYCLE - 2) + ["        sta RESP0         ; re-park P0 to x=3"]
L += pad(P1_PARK_CYCLE - 2 - PARK_CYCLE - 1) + [
    "        sta RESP1         ; park P1 at x=%d" % (3 * P1_PARK_CYCLE - 60)]
lines += 1
L.append("        sta WSYNC         ; sentinel: P0's parked three (P1 is still dark)")
lines += 1
L.append("        sta WSYNC")
L.append("        lda #$FF")
L.append("        sta GRP1          ; P1 lights up only for this one measurement line")
cy = 5
for c, reg in both:
    L += pad(c - 2 - cy)
    L.append("        sta %-6s          ; write cycle %d" % (reg, c))
    cy = c + 1
lines += 1
# GRP1 goes dark on the NEXT line, not this one. Clearing it after the last strobe put the write at
# cycle 61 -- beam x=115 -- and silently cut P1's last two copies, which read as "two players reach
# fourteen" until the listing was counted.
L.append("        sta WSYNC         ; P1 stays lit to the end of its measurement line")
lines += 1
L.append("        lda #$00")
L.append("        sta GRP1")

rest = 192 - lines
if rest < 1:
    raise SystemExit("picture is %d lines, over budget" % lines)
L += ["        lda #0", "        sta GRP0",
      "        ldx #%d" % rest, "Rest:   sta WSYNC", "        dex", "        bne Rest",
      "        lda #2", "        sta VBLANK",
      "        ldx #30", "OsPad:  sta WSYNC", "        dex", "        bne OsPad",
      "        jmp Frame",
      "        org $FFFC", "        word Reset", "        word Reset"]

asm = os.path.join(ROOT, "roms", "litmus", "litmus_restrobe.asm")
binp = os.path.join(ROOT, "roms", "litmus", "litmus_restrobe.bin")
open(asm, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", asm, "-f3", "-o" + binp], check=True)
print("%d picture lines, %d spacing bands + 1 two-player band" % (lines, len(BANDS)))
print("bands in order: %s" % ", ".join(tag for tag, _ in BANDS))
