#!/usr/bin/env python3
"""Generate `roms/litmus/litmus_respx_phase.asm` — the RESPx / RESMx / RESBL reset phase.

Closes `docs/fundamentals-audit.md:43`, which harness itself marks 📖 — its own legend
defines that as "stated by a document, NOT measured by our litmus ROMs". The claim:

    RESPx pipeline (Towers): counter reset -> first visible copy appears 5px right of
    the reset.

Measured 2026-09-03 with sl_shoot --five: layer (2) techniques/roms and layer (3)
internal+cmd+pkg+Gopher2600/hardware both return 0 for that phrase, so nothing in the
tree grades it. Meanwhile `litmus_jmpind_pos` and `plan_sprite_placement` both measure
their own x0 empirically instead of predicting it, precisely because this constant was
never pinned.

Shape: one band per strobe cycle. The kernel burns a known number of CPU cycles after
WSYNC, strobes one object's reset, and holds the position for the rest of the band. The
grading test reads the drawn pixel and fits x = 3*c + k, so k is measured rather than
assumed - and it is measured separately for the player (an 8-clock object with a
serial-shift pipeline) and for the missile and ball (1-clock objects), because the
document's "5px" is stated for RESPx alone and the difference between the three is the
discriminating evidence.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "roms", "litmus", "litmus_respx_phase.asm")
BIN = os.path.join(ROOT, "roms", "litmus", "litmus_respx_phase.bin")

# One `dec scratch` = 5 CPU cycles = 15 colour clocks. To sweep the strobe across a
# useful stretch of the visible line in 3-clock steps we need a 1-cycle unit, so the
# delay is built from `nop` (2cy) and `bit scratch` (3cy) instead: n cycles = a mix.
#
# DELAYS is the extra CPU cycles inserted before the strobe, per band. Consecutive
# values differ by 1, so consecutive bands differ by exactly 3 colour clocks - the
# finest step the CPU can make, and the step the fit needs to be sensitive.
# 2 is the floor: the 6502 has no one-cycle instruction, so a delay of exactly 1 cycle
# cannot be built from nop (2) and bit zp (3). Every value from 2 up can. The sweep
# therefore runs 2..17, which is still 16 bands at 3 colour clocks apart.
DELAYS = list(range(2, 18))          # 16 bands per object, 3 clocks apart
# M0 shares COLUP0 with P0, so a frame carrying both cannot be read apart by colour -
# the first version of this fixture did that and the probe could not tell which white
# pixel it had found. M1 has its own COLUP1, so the three objects are three colours.
OBJECTS = [("RESP0", "GRP0", "COLUP0", "$0E"),   # player: 8-clock object, white
           ("RESM1", None,   "COLUP1", "$B6"),   # missile 1: 1-clock, green
           ("RESBL", None,   "COLUPF", "$46")]   # ball: 1-clock, red
BAND = 4                             # scanlines per band: strobe, then 3 held
BASE_DECS = 4                        # 4 x `dec scratch` = 20cy, lands band 0 on screen
VISIBLE = 192


def delay(cy):
    """Emit exactly `cy` CPU cycles of delay using nop (2) and bit zp (3).

    A greedy "take 3s first" pass leaves a remainder of 1 on even inputs (4 -> 3 + 1)
    and 1 is not constructible, so decompose by parity instead: one `bit` when the
    total is odd, `nop` for everything left. Every cy >= 2 is then exact, and cy == 1
    is refused rather than silently rounded - a delay that is off by one cycle moves
    the strobe three colour clocks and the fit would absorb it as phase.
    """
    if cy == 0:
        return []
    assert cy >= 2, "cy=1 is not constructible on 6502 (no one-cycle instruction)"
    out = []
    n = cy
    if n % 2:
        out.append("        bit scratch         ; 3 cy")
        n -= 3
    while n > 0:
        out.append("        nop                 ; 2 cy")
        n -= 2
    assert n == 0, cy
    return out


bands = [(obj, d) for obj, _g, _c, _i in OBJECTS for d in DELAYS]
used = len(bands) * BAND
assert used <= VISIBLE, (used, VISIBLE)

L = []
w = L.append
w("; litmus_respx_phase — the reset-strobe phase for RESP0 / RESM0 / RESBL")
w(";   (GENERATED by scripts/gen_litmus_respx_phase.py — edit that, not this file)")
w(";")
w("; Closes docs/fundamentals-audit.md:43, which harness marks 📖 = documented, NOT")
w("; measured. Claim under test: 'counter reset -> first visible copy appears 5px right")
w("; of the reset' (Towers, TIA Hardware Notes), stated for RESPx.")
w(";")
w("; One band per strobe cycle; consecutive bands strobe 1 CPU cycle = 3 colour clocks")
w("; later. The grading test fits x = 3*c + k and reports k per object, so the phase is")
w("; measured, and measured separately for the 8-clock player and the 1-clock missile")
w("; and ball.")
w(";")
w("; %d bands x %d lines = %d picture lines, %d blank." % (len(bands), BAND, used, VISIBLE - used))
w("        processor 6502")
w("VSYNC   = $00")
w("VBLANK  = $01")
w("WSYNC   = $02")
w("NUSIZ0  = $04")
w("COLUP0  = $06")
w("COLUP1  = $07")
w("COLUPF  = $08")
w("COLUBK  = $09")
w("CTRLPF  = $0A")
w("RESP0   = $10")
# RESP0=$10 RESP1=$11 RESM0=$12 ★RESM1=$13 RESBL=$14. The first version of this
# generator wrote RESM1 = $12, which is RESM0 - and with only ENAM1 set nothing
# visible moved, so the probe read a constant 25 across all sixteen missile bands.
# A wrong strobe address looks exactly like "the object does not respond".
w("RESM1   = $13")
w("RESBL   = $14")
w("GRP0    = $1B")
w("ENAM1   = $1E")
w("ENABL   = $1F")
w("HMCLR   = $2B")
w("scratch = $82")
w("")
w("        org $F000")
w("Start:")
w("        sei")
w("        cld")
w("        ldx #$FF")
w("        txs")
w("        lda #0")
w("Clr:    sta $00,x")
w("        dex")
w("        bne Clr")
w("        sta HMCLR           ; every HMxx zero for the whole run")
w("        sta CTRLPF          ; ball 1 clock wide, no reflect, no score")
w("        sta NUSIZ0          ; player 1x, missile 1 clock")
w("        lda #$0E")
w("        sta COLUP0          ; white: player and missile")
w("        lda #$46")
w("        sta COLUPF          ; red: ball")
w("        lda #$B6")
w("        sta COLUP1          ; green: missile 1")
w("        lda #$80")
w("        sta GRP0            ; one pixel, leftmost bit of the player")
w("        lda #2")
w("        sta ENAM1")
w("        sta ENABL")
w("")
w("NextFrame:")
w("        lda #2")
w("        sta VSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        lda #0")
w("        sta VSYNC")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #37")
w("VB:     sta WSYNC")
w("        dex")
w("        bne VB")
w("        lda #0")
w("        sta VBLANK")
w("")
for obj, d in bands:
    w("        ; --- %s, +%d cy ---" % (obj, d))
    w("        sta WSYNC")
    for _ in range(BASE_DECS):
        w("        dec scratch         ; 5 cy")
    L.extend(delay(d))
    w("        sta %-15s ; strobe" % obj)
    for _ in range(BAND - 1):
        w("        sta WSYNC")
w("")
# `ldx #0` is a 256-iteration loop, not a zero-iteration one, so the filler has to be
# omitted when the bands already fill the picture. Leaving it in produced a 35-scanline
# frame - the first version of this generator did exactly that.
if VISIBLE - used > 0:
    w("        ldx #%d" % (VISIBLE - used))
    w("Fill:   sta WSYNC")
    w("        dex")
    w("        bne Fill")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #30")
w("OS:     sta WSYNC")
w("        dex")
w("        bne OS")
w("        jmp NextFrame")
w("")
w("        org $FFFC")
w("        .word Start")
w("        .word Start")

open(ASM, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", ASM, "-f3", "-o" + BIN], check=True)
print("%d bands (%d objects x %d delays), %d picture lines used, %d blank"
      % (len(bands), len(OBJECTS), len(DELAYS), used, VISIBLE - used))
print("objects: %s" % ", ".join(o for o, _g, _c, _i in OBJECTS))
print("delays : %s cy (each +1 cy = +3 colour clocks)" % DELAYS)
