#!/usr/bin/env python3
"""Build roms/litmus/litmus_restrobe.asm/.bin — what a mid-line RESP strobe is worth.

Graded by internal/emu/restrobe_test.go; the rules are in docs/techniques/restrobe-copies.md.

Six bands of three scanlines. P0 is parked at x=3 with NUSIZ=3 (three copies, sixteen apart) while
the screen is still blank, then band k re-strobes RESP0 k times on one picture line, eight cycles
apart, and the line after it is left alone so the parked pattern can be read back for comparison.

    band k, line 0   k re-strobes on this line
    band k, line 1   untouched -- three copies, the baseline
    band k, line 2   RESP0 back to x=3, so every band starts from the same place

The question this settles is whether a strobe MOVES the copies or ADDS to them. Three probes in the
work that prompted this said "moves", and all three were built the same wrong way: the claim is
about a copy SEQUENCE restarting, and each of them measured a player with ONE copy.
"""
import os, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PARK_CYCLE = 21          # the RESP0 WRITE cycle that parks the player at its leftmost, x=3
STROBES = [[], [29], [29, 37], [29, 37, 45], [29, 37, 45, 53], [29, 37, 45, 53, 61]]


def pad(n):
    """n cycles of nothing. nop is 2 and bit on zero page is 3, so one cycle cannot be built."""
    if n < 0 or n == 1:
        raise SystemExit("pad %d cannot be built" % n)
    out = []
    if n % 2:
        out.append("        bit $80"); n -= 3
    return out + ["        nop"] * (n // 2)


L = ["; litmus_restrobe.asm — GENERATED by scripts/gen_litmus_restrobe.py. Do not hand-edit.",
     "; Six bands of three lines: k re-strobes, then an untouched line, then a line that re-parks.",
     "        processor 6502",
     "VSYNC = $00", "VBLANK = $01", "WSYNC = $02", "NUSIZ0 = $04",
     "COLUP0 = $06", "COLUBK = $09", "GRP0 = $1B", "RESP0 = $10",
     "        org $F000",
     "Reset:  sei", "        cld", "        ldx #0", "        txa",
     "Clear:  dex", "        txs", "        pha", "        bne Clear",
     "        lda #$00", "        sta COLUBK",
     "        lda #$0E", "        sta COLUP0",
     "        lda #$03", "        sta NUSIZ0        ; three copies, sixteen apart",
     "Frame:  lda #2", "        sta VSYNC",
     "        sta WSYNC", "        sta WSYNC", "        sta WSYNC",
     "        lda #0", "        sta VSYNC",
     "        ldx #35", "VbPad:  sta WSYNC", "        dex", "        bne VbPad",
     "        sta WSYNC"] + pad(PARK_CYCLE - 2) + [
     "        sta RESP0         ; write cycle %d -> x = 3c-60 = 3, the leftmost a player reaches" % PARK_CYCLE,
     "        lda #0", "        sta VBLANK",
     "        lda #$FF", "        sta GRP0"]

lines = 0
for k, cs in enumerate(STROBES):
    L.append("; ---- band %d: %d re-strobe(s) ----" % (k, len(cs)))
    L.append("        sta WSYNC")
    cyc = 0
    for c in cs:
        L += pad(c - 2 - cyc) + ["        sta RESP0         ; write cycle %d -> base x=%d" % (c, 3*c-60)]
        cyc = c + 1      # c is the store's LAST cycle; the next free one is c+1
    lines += 1
    L.append("        sta WSYNC         ; untouched: the parked three")
    lines += 1
    L.append("        sta WSYNC")
    L += pad(PARK_CYCLE - 2) + ["        sta RESP0         ; back to x=3"]
    lines += 1

rest = 192 - lines
L += ["        lda #0", "        sta GRP0",
      "        ldx #%d" % rest, "Rest:   sta WSYNC", "        dex", "        bne Rest",
      "        lda #2", "        sta VBLANK",
      "        ldx #30", "OsPad:  sta WSYNC", "        dex", "        bne OsPad",
      "        jmp Frame",
      "        org $FFFC", "        word Reset", "        word Reset"]

asm = os.path.join(ROOT, "roms", "litmus", "litmus_restrobe.asm")
binp = os.path.join(ROOT, "roms", "litmus", "litmus_restrobe.bin")
open(asm, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", asm, "-f3", "-o" + binp], check=True)
print("%d picture lines, %d bands" % (lines, len(STROBES)))
