#!/usr/bin/env python3
"""Generate `roms/litmus/litmus_missile_novdel.asm` — missiles have no delay path.

Closes `docs/fundamentals-audit.md` "Missiles have **no** vertical delay (so in a 2LK
they start only on even lines)", marked 📖 = stated by a document, not measured here.
Layers (1), (2) and (3) all return 0 for it.

The claim is best read against the ball, which DOES have one: `litmus_vdel_cross` shows
that with VDELBL set, ENABL's new copy is invisible until a GRP1 write latches it. If
missiles had the same path there would be a VDELM register and the same latch; the
document says there is not.

So the fixture puts the two side by side under identical conditions - every VDEL bit
set, both objects enabled on the same line, no GRP write afterwards:

  the ball    must stay DARK    (its new copy is waiting for a latch that never comes)
  the missile must appear LIT   (it has no new/old pair to wait on)

One frame, one line, two colours, opposite answers. A fixture that showed both lit or
both dark would mean the delay path is not where the document puts it.

Band C then writes GRP1 and the ball joins the missile, which is the control: it proves
the ball was dark for the documented reason - a pending latch - and not because the
fixture failed to enable it.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "roms", "litmus", "litmus_missile_novdel.asm")
BIN = os.path.join(ROOT, "roms", "litmus", "litmus_missile_novdel.bin")

BAND = 10
VISIBLE = 192

L = []
w = L.append
w("; litmus_missile_novdel — missiles have no vertical-delay path; the ball does")
w(";   (GENERATED by scripts/gen_litmus_missile_novdel.py — edit that, not this file)")
w(";")
w("; Closes the 📖 'Missiles have no vertical delay'. Read against the ball, which does")
w("; have one: with VDELBL set, ENABL's new copy waits for a GRP1 write. The missile has")
w("; no such pair, so it lights immediately under the same conditions.")
w("        processor 6502")
w("VSYNC   = $00")
w("VBLANK  = $01")
w("WSYNC   = $02")
w("COLUP0  = $06")
w("COLUPF  = $08")
w("COLUBK  = $09")
w("RESM0   = $12")
w("RESBL   = $14")
w("GRP0    = $1B")
w("GRP1    = $1C")
w("ENAM0   = $1D")
w("ENABL   = $1F")
w("VDELP0  = $25")
w("VDELP1  = $26")
w("VDELBL  = $27")
w("HMCLR   = $2B")
w("")
w("        org $F000")
w("Start:")
w("        sei")
w("        cld")
w("        ldx #$FF")
w("        txs")
w("        lda #0")
w("Clr:    sta $00,x")
w("        dex")
w("        bne Clr")
w("        sta HMCLR")
w("        lda #$0E")
w("        sta COLUP0          ; white = missile 0")
w("        lda #$46")
w("        sta COLUPF          ; red   = ball")
w("")
w("NextFrame:")
w("        lda #2")
w("        sta VSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        lda #0")
w("        sta VSYNC")
w("        lda #2")
w("        sta VBLANK")
w("        sta WSYNC")
w("        ldx #6")
w("Ma:     dex")
w("        bne Ma")
w("        sta RESM0")
w("        ldx #8")
w("Mb:     dex")
w("        bne Mb")
w("        sta RESBL           ; the two sit in different columns")
w("        ldx #35")
w("VB:     sta WSYNC")
w("        dex")
w("        bne VB")
w("        lda #0")
w("        sta VBLANK")
w("")


def clear():
    w("        sta WSYNC")
    w("        lda #0")
    w("        sta ENAM0")
    w("        sta ENABL")
    w("        sta VDELP0")
    w("        sta VDELP1")
    w("        sta VDELBL")
    # Latch every old copy to zero, so no band can pass on state left by an earlier one
    # or by the previous frame. litmus_vdel_cross found that defect the hard way.
    w("        sta GRP1")
    w("        sta GRP0")


# A: every delay bit set, both objects enabled, no GRP write after.
w("        ; ===== A  all VDEL set, both enabled, no latch =====")
clear()
w("        sta WSYNC")
w("        lda #1")
w("        sta VDELBL          ; the ball will display its OLD copy")
w("        lda #2")
w("        sta ENAM0           ; missile: no old/new pair to wait on")
w("        sta ENABL           ; ball: new copy set, old still zero")
for _ in range(BAND - 2):
    w("        sta WSYNC")

# B: the same, but VDELBL clear — both must be lit, which shows the fixture enables both.
w("        ; ===== B  VDELBL clear: both must be lit =====")
clear()
w("        sta WSYNC")
w("        lda #2")
w("        sta ENAM0")
w("        sta ENABL")
for _ in range(BAND - 2):
    w("        sta WSYNC")

# C: VDELBL set, then a GRP1 write latches the ball. Both lit again.
w("        ; ===== C  VDELBL set, then GRP1 latches the ball =====")
clear()
w("        sta WSYNC")
w("        lda #1")
w("        sta VDELBL")
w("        lda #2")
w("        sta ENAM0")
w("        sta ENABL")
w("        lda #0")
w("        sta GRP1            ; latches ENABL new->old")
for _ in range(BAND - 2):
    w("        sta WSYNC")

w("        ; ===== clear before the filler =====")
clear()

used = 3 * BAND + 1
if VISIBLE - used > 0:
    w("        ldx #%d" % (VISIBLE - used))
    w("Fill:   sta WSYNC")
    w("        dex")
    w("        bne Fill")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #30")
w("OS:     sta WSYNC")
w("        dex")
w("        bne OS")
w("        jmp NextFrame")
w("")
w("        org $FFFC")
w("        .word Start")
w("        .word Start")

open(ASM, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", ASM, "-f3", "-o" + BIN], check=True)
print("3 bands x %d lines = %d picture lines, %d blank" % (BAND, used, VISIBLE - used))
