#!/usr/bin/env python3
"""Generate `roms/litmus/litmus_jmpind_pos.asm` — indirect-jump object positioning.

Backs the claim recorded in `docs/design-principles.md` that an object can be placed
by dispatching through `JMP (ptr)` into a table of hardcoded positioning lines, with
no cycle-counting delay loop in the kernel.

Primary source: Stella mailing list, `star fire - return of the starfield ?!?`,
2002-07, Erik Mooney (200207/msg00330, msg00334) and Manuel Polik (msg00332).
Erik's sketch, verbatim from msg00330:

        STA HMCLR
        LDA [SpriteHMove]
        STA HMP0
        JMP [SpritePosAddr]   ; jumps to one of Label#
    Label1: instruction1 / instruction2 / STA RESP0 / ... / JMP EndOfLine
    Label2: instruction1 ... instruction4 / STA RESP0 / ... / JMP EndOfLine
    EndOfLine: STA WSYNC / STA HMOVE

Manuel's arithmetic under test (msg00332): "I'd only need 9 kernel parts, as there
are only 128 horizontal positions."  A coarse step is 5 CPU cycles = 15 colour
clocks, so 9 variants span 8*15 = 120 clocks; HMOVE's fine range is -7..+8 = 16
values.  Coverage is contiguous only because the fine range (16) is at least the
coarse step (15) — one fewer fine value and the reachable set has holes.  The
grading test checks the span, the step, and that no gap exists.

Band table order is a PERMUTATION, not 0..8: a kernel that positioned by band index
rather than by the dispatched variant would draw a monotone ramp and pass an ordered
table.  Nothing here is monotone.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "roms", "litmus", "litmus_jmpind_pos.asm")
BIN = os.path.join(ROOT, "roms", "litmus", "litmus_jmpind_pos.bin")

NVAR = 9            # variants; Manuel's "9 kernel parts"
BASE_DECS = 4       # DEC zp = 5 cycles each, before the dispatch, to land k=0 on screen
COARSE_ORDER = [4, 0, 5, 2, 8, 1, 6, 3, 7]      # non-monotone, and never ends on FINE_COARSE
FINE_NIBBLES = [0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7,
                0x8, 0x9, 0xA, 0xB, 0xC, 0xD, 0xE, 0xF]
FINE_COARSE = 4     # the fine sweep sits on the middle variant
LINES_PER_BAND = 5  # setup, position, hmove, draw, draw
VISIBLE = 192

bands = [(k, 0x00) for k in COARSE_ORDER] + [(FINE_COARSE, n << 4) for n in FINE_NIBBLES]
used = len(bands) * LINES_PER_BAND
assert used <= VISIBLE, (used, VISIBLE)

L = []
w = L.append
w("; litmus_jmpind_pos — indirect-jump object positioning (GENERATED by")
w(";   scripts/gen_litmus_jmpind_pos.py — edit that, not this file)")
w(";")
w("; Claim: `JMP (ptr)` into a table of hardcoded positioning lines places an object")
w(";        at x(k) = x(0) + 15k, with NO cycle-counting delay loop in the kernel.")
w("; Source: Stella list, star fire - return of the starfield ?!?, 2002-07,")
w(";         Erik Mooney 200207/msg00330+00334; Manuel Polik 200207/msg00332.")
w(";")
w("; P0 (COLUP0, GRP0=$80 = one pixel) is the dispatched object.")
w("; BL (COLUPF) is the static control: positioned once, never re-strobed.")
w("; Band order is a permutation, so a band-index artefact cannot pass.")
w(";")
w(f"; {len(bands)} bands x {LINES_PER_BAND} lines = {used} picture lines, "
  f"{VISIBLE - used} blank.")
w("        processor 6502")
w("VSYNC   = $00")
w("VBLANK  = $01")
w("WSYNC   = $02")
w("NUSIZ0  = $04")
w("COLUP0  = $06")
w("COLUPF  = $08")
w("COLUBK  = $09")
w("RESP0   = $10")
w("RESBL   = $14")
w("GRP0    = $1B")
w("ENABL   = $1F")
w("HMP0    = $20")
w("HMOVE   = $2A")
w("HMCLR   = $2B")
w("ptr     = $80")
w("scratch = $82        ; DEC target used purely to burn 5 cycles")
w("band    = $83")
w("")
w("        org $F000")
w("Start:")
w("        sei")
w("        cld")
w("        ldx #$FF")
w("        txs")
w("        lda #0")
w("Clr:    sta $00,x")
w("        dex")
w("        bne Clr")
w("        sta HMCLR")
w("        lda #$00")
w("        sta COLUBK          ; black")
w("        lda #$0E")
w("        sta COLUP0          ; white dot = the dispatched object")
w("        lda #$46")
w("        sta COLUPF          ; red bar = the static control")
w("        lda #$80")
w("        sta GRP0            ; one pixel, leftmost bit")
w("        lda #0")
w("        sta NUSIZ0")
w("        lda #$02")
w("        sta ENABL           ; ball on, 1 clock wide (CTRLPF=0)")
w("")
w("NextFrame:")
w("        lda #2")
w("        sta VSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        lda #0")
w("        sta VSYNC")
w("        lda #2")
w("        sta VBLANK")
w("        ; --- the static control: RESBL once per frame at a fixed cycle, far right")
w("        sta WSYNC")
w("        ldx #12")
w("Bd:     dex")
w("        bne Bd              ; 2 + 5*11 + 4 = 61 cy")
w("        sta RESBL")
w("        sta HMCLR")
w("        ldx #36")
w("VB:     sta WSYNC")
w("        dex")
w("        bne VB")
w("        lda #0")
w("        sta VBLANK")
w("")
w("        ; ================= bands =================")
w("        ldx #0")
w("        stx band")
w("Band:")
w("        ; --- setup line: load the dispatch pointer and the fine nibble")
w("        sta WSYNC")
w("        ldx band")
w("        lda TabLo,x")
w("        sta ptr")
w("        lda TabHi,x")
w("        sta ptr+1")
w("        lda TabFine,x")
w("        sta HMP0")
w("        ; --- positioning line: base delay, then the indirect dispatch")
w("        sta WSYNC")
for _ in range(BASE_DECS):
    w("        dec scratch         ; 5 cy")
w("        jmp (ptr)           ; 5 cy -> one of Pos0..Pos%d" % (NVAR - 1))
w("        ; unreachable by construction; a poison here would never execute")
w("")
w("AfterPos:")
w("        sta WSYNC")
w("        sta HMOVE           ; apply the fine nibble (0 for the coarse bands)")
w("        sta WSYNC           ; draw line 1  <- graded")
w("        sta WSYNC           ; draw line 2  <- graded")
w("        sta HMCLR")
w("        inc band")
w("        lda band")
w("        cmp #%d" % len(bands))
w("        bne Band")
w("")
w("        ; --- remaining picture lines, nothing moves")
w("        ldx #%d" % (VISIBLE - used))
w("Fill:   sta WSYNC")
w("        dex")
w("        bne Fill")
w("")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #30")
w("OS:     sta WSYNC")
w("        dex")
w("        bne OS")
w("        jmp NextFrame")
w("")
w("; ---- the unrolled positioning lines: variant k strobes 5k cycles later ----")
for k in range(NVAR):
    w("Pos%d:" % k)
    for _ in range(k):
        w("        dec scratch         ; 5 cy")
    w("        sta RESP0           ; 3 cy")
    w("        jmp AfterPos        ; 3 cy")
w("")
w("; ---- band tables ----")
w("TabLo:")
w("        .byte " + ", ".join("#<Pos%d" % k for k, _ in bands))
w("TabHi:")
w("        .byte " + ", ".join("#>Pos%d" % k for k, _ in bands))
w("TabFine:")
w("        .byte " + ", ".join("$%02X" % f for _, f in bands))
w("")
w("        org $FFFC")
w("        .word Start")
w("        .word Start")

os.makedirs(os.path.dirname(ASM), exist_ok=True)
open(ASM, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", ASM, "-f3", "-o" + BIN], check=True)
print("%d bands (%d coarse + %d fine), %d picture lines used, %d blank"
      % (len(bands), NVAR, len(FINE_NIBBLES), used, VISIBLE - used))
print("coarse order (non-monotone): %s" % COARSE_ORDER)
print("wrote %s and %s" % (os.path.relpath(ASM, ROOT), os.path.relpath(BIN, ROOT)))
