#!/usr/bin/env python3
"""Generate `roms/litmus/litmus_vdel_cross.asm` — VDEL's write-triggered cross-copy.

Closes `docs/fundamentals-audit.md:70`, marked 📖 = stated by a document, not measured
here. The claim, from Stella PG §6.D, and harness calls it "the load-bearing mechanism":

    each GRP has new+old copies. Writing GRP0 copies P1's new->old; writing GRP1 copies
    P0's new->old, AND ALSO ENABL's new->old. VDELPx/VDELBL D0=1 selects the old copy.

The vendored engine implements exactly that (`hardware/tia/video/video.go:234-238`:
GRP0 -> Player1.setOldGfxData; GRP1 -> Player0.setOldGfxData AND Ball.setEnableDelay),
and nothing in the tree asserts it. The ball half is the strange one - a write to a
PLAYER register moving the BALL's enable - and it is also the one that gives a clean
binary reading, which is why this fixture leads with it.

Bands, each 8 lines:

  A  VDELBL on, ENABL set, then write GRP0   -> ball stays OFF   (GRP0 must not latch it)
  B  VDELBL on, ENABL set, then write GRP1   -> ball turns ON    (GRP1 latches it)
  C  VDELP0 on, GRP0 loaded then cleared, GRP1 written in between -> P0 shows the OLD byte
  D  VDELP1 on, GRP1 loaded then cleared, GRP0 written in between -> P1 shows the OLD byte

A and B differ by one instruction. That is the whole measurement: if the ball is on in
both, or off in both, the cross-copy is not what the document says.
"""
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(ROOT, "roms", "litmus", "litmus_vdel_cross.asm")
BIN = os.path.join(ROOT, "roms", "litmus", "litmus_vdel_cross.bin")

BAND = 8
VISIBLE = 192

L = []
w = L.append
w("; litmus_vdel_cross — VDEL's write-triggered cross-copy between GRP0/GRP1/ENABL")
w(";   (GENERATED by scripts/gen_litmus_vdel_cross.py — edit that, not this file)")
w(";")
w("; Closes docs/fundamentals-audit.md:70. Claim (Stella PG 6.D): writing GRP0 copies")
w("; P1's new->old; writing GRP1 copies P0's new->old AND ENABL's new->old.")
w("; Bands A and B differ by ONE instruction — GRP0 vs GRP1 — and the ball's visibility")
w("; is the reading.")
w("        processor 6502")
w("VSYNC   = $00")
w("VBLANK  = $01")
w("WSYNC   = $02")
w("COLUP0  = $06")
w("COLUP1  = $07")
w("COLUPF  = $08")
w("COLUBK  = $09")
w("RESP0   = $10")
w("RESP1   = $11")
w("RESBL   = $14")
w("GRP0    = $1B")
w("GRP1    = $1C")
w("ENABL   = $1F")
w("VDELP0  = $25")
w("VDELP1  = $26")
w("VDELBL  = $27")
w("HMCLR   = $2B")
w("scratch = $82")
w("")
w("        org $F000")
w("Start:")
w("        sei")
w("        cld")
w("        ldx #$FF")
w("        txs")
w("        lda #0")
w("Clr:    sta $00,x")
w("        dex")
w("        bne Clr")
w("        sta HMCLR")
w("        lda #$0E")
w("        sta COLUP0          ; white  = P0")
w("        lda #$B6")
w("        sta COLUP1          ; green  = P1")
w("        lda #$46")
w("        sta COLUPF          ; red    = ball")
w("")
w("NextFrame:")
w("        lda #2")
w("        sta VSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        sta WSYNC")
w("        lda #0")
w("        sta VSYNC")
w("        lda #2")
w("        sta VBLANK")
w("        ; place the three objects apart so each colour has its own column")
w("        sta WSYNC")
w("        ldx #4")
w("Pa:     dex")
w("        bne Pa")
w("        sta RESP0")
w("        ldx #4")
w("Pb:     dex")
w("        bne Pb")
w("        sta RESP1")
w("        ldx #4")
w("Pc:     dex")
w("        bne Pc")
w("        sta RESBL")
w("        ldx #35")
w("VB:     sta WSYNC")
w("        dex")
w("        bne VB")
w("        lda #0")
w("        sta VBLANK")
w("")


def band(tag, body):
    w("        ; ===== %s =====" % tag)
    w("        sta WSYNC")
    w("        lda #0")
    w("        sta GRP0")
    w("        sta GRP1")
    w("        sta ENABL")
    w("        sta VDELP0")
    w("        sta VDELP1")
    w("        sta VDELBL")
    # Clearing the NEW copies is not enough: the OLD copies survive from earlier bands and
    # from the previous frame, so a band could read as a pass on stale state. Write GRP1
    # and GRP0 once here, while everything is zero, to latch old := 0 for the ball and for
    # both players. Measured: without this, replacing band B's GRP1 with GRP0 - which
    # should destroy the effect being tested - still left the ball lit, because its old
    # copy had been latched to 1 by a previous frame.
    w("        sta GRP1            ; latch old := 0 (ball + P0)")
    w("        sta GRP0            ; latch old := 0 (P1)")
    for line in body:
        w(line)
    for _ in range(BAND - 2):
        w("        sta WSYNC")


# A: VDELBL on, ENABL set, then write GRP0. The ball must stay dark.
band("A  VDELBL, ENABL, then GRP0 -> ball must stay OFF", [
    "        sta WSYNC",
    "        lda #1",
    "        sta VDELBL          ; display the OLD enable",
    "        lda #2",
    "        sta ENABL           ; NEW enable = on; old is still off",
    "        lda #$00",
    "        sta GRP0            ; writing GRP0 must NOT latch the ball",
])
# B: same, but GRP1. The ball must appear.
band("B  VDELBL, ENABL, then GRP1 -> ball must turn ON", [
    "        sta WSYNC",
    "        lda #1",
    "        sta VDELBL",
    "        lda #2",
    "        sta ENABL",
    "        lda #$00",
    "        sta GRP1            ; writing GRP1 copies ENABL new->old",
])
# C: P0 shows its OLD byte once GRP1 has latched it.
band("C  VDELP0, GRP0=$FF, GRP1 latches it, GRP0=$00 -> P0 shows $FF", [
    "        sta WSYNC",
    "        lda #1",
    "        sta VDELP0",
    "        lda #$FF",
    "        sta GRP0            ; new = $FF",
    "        lda #$00",
    "        sta GRP1            ; copies P0 new->old, so old = $FF",
    "        sta GRP0            ; new = $00; the display uses old",
])
# D: the mirror — P1's old is latched by a GRP0 write.
band("D  VDELP1, GRP1=$FF, GRP0 latches it, GRP1=$00 -> P1 shows $FF", [
    "        sta WSYNC",
    "        lda #1",
    "        sta VDELP1",
    "        lda #$FF",
    "        sta GRP1            ; new = $FF",
    "        lda #$00",
    "        sta GRP0            ; copies P1 new->old, so old = $FF",
    "        sta GRP1            ; new = $00; the display uses old",
])

# Clear everything before the filler. Without this the last band's objects stay lit all
# the way down the picture, and a geometry check that asks "is anything drawn past the
# bands?" reads the leftovers rather than a fault.
w("        ; ===== clear before the filler =====")
w("        sta WSYNC")
w("        lda #0")
w("        sta GRP0")
w("        sta GRP1")
w("        sta ENABL")
w("        sta VDELP0")
w("        sta VDELP1")
w("        sta VDELBL")

used = 4 * BAND + 1
if VISIBLE - used > 0:
    w("        ldx #%d" % (VISIBLE - used))
    w("Fill:   sta WSYNC")
    w("        dex")
    w("        bne Fill")
w("        lda #2")
w("        sta VBLANK")
w("        ldx #30")
w("OS:     sta WSYNC")
w("        dex")
w("        bne OS")
w("        jmp NextFrame")
w("")
w("        org $FFFC")
w("        .word Start")
w("        .word Start")

open(ASM, "w").write("\n".join(L) + "\n")
subprocess.run(["dasm", ASM, "-f3", "-o" + BIN], check=True)
print("4 bands x %d lines = %d picture lines, %d blank" % (BAND, used, VISIBLE - used))
