; monet_m1 — generated by cmd/genpf (internal/playfield.GenerateSymmetricASM)
; 対称(reflect) playfield 静止画。行数=48 行高=4 scanline。左半を描き右半は鏡像。
        processor 6502
VSYNC   = $00
VBLANK  = $01
WSYNC   = $02
COLUPF  = $08
COLUBK  = $09
CTRLPF  = $0A
PF0     = $0D
PF1     = $0E
PF2     = $0F
PFHGT   = $80          ; 行高カウンタ(RAM)

        org $F000
Start:
        sei
        cld
        ldx #$FF
        txs
        lda #0
Clr:    sta $00,x
        dex
        bne Clr
        lda #1
        sta CTRLPF      ; reflect（右半=左半の鏡像）

NextFrame:
        lda #2
        sta VBLANK
        sta VSYNC
        sta WSYNC
        sta WSYNC
        sta WSYNC
        lda #0
        sta VSYNC
        ldx #37
VBlank: sta WSYNC
        dex
        bne VBlank
        lda #0
        sta VBLANK

        ldx #47           ; 行インデックス（rows-1, TOP から下る）
        lda #4
        sta PFHGT
PFLoop:
        sta WSYNC
        lda BGColors,x    ; 水背景（行全体に効くので先頭）
        sta COLUBK
        lda PF0Data,x     ; PF0/1/2 を just-in-time で
        sta PF0
        lda PF1Data,x
        sta PF1
        lda PF2Data,x
        sta PF2
        lda PFColors,x    ; lily 色（最後）
        sta COLUPF
        dec PFHGT
        bne PFSame
        lda #4
        sta PFHGT
        dex
        bmi PFDone
PFSame:
        jmp PFLoop
PFDone:
        lda #0
        sta PF0
        sta PF1
        sta PF2
        sta COLUBK
        lda #2
        sta VBLANK
        ldx #30
OScan:  sta WSYNC
        dex
        bne OScan
        jmp NextFrame

PF0Data
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $80
        .byte $80
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $E0
        .byte $E0
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $C0
        .byte $C0
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PF1Data
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $07
        .byte $07
        .byte $00
        .byte $00
        .byte $00
        .byte $E0
        .byte $E0
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $0F
        .byte $0F
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $7C
        .byte $7C
        .byte $00
        .byte $00
        .byte $00
        .byte $01
        .byte $01
        .byte $00
        .byte $C0
        .byte $C0
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PF2Data
        .byte $00
        .byte $00
        .byte $00
        .byte $78
        .byte $78
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $1F
        .byte $1F
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $3C
        .byte $3C
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $03
        .byte $03
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00
        .byte $00

PFColors
        .byte $46
        .byte $CA
        .byte $4A
        .byte $C6
        .byte $4C
        .byte $F6
        .byte $CA
        .byte $4A
        .byte $CA
        .byte $C6
        .byte $C6
        .byte $CA
        .byte $C8
        .byte $4C
        .byte $CC
        .byte $CC
        .byte $CA
        .byte $C8
        .byte $C8
        .byte $F8
        .byte $C8
        .byte $CA
        .byte $CC
        .byte $CC
        .byte $C6
        .byte $C6
        .byte $CA
        .byte $FC
        .byte $4A
        .byte $C8
        .byte $CA
        .byte $C8
        .byte $4A
        .byte $4A
        .byte $F8
        .byte $F6
        .byte $C6
        .byte $C8
        .byte $C6
        .byte $FA
        .byte $CA
        .byte $C8
        .byte $C8
        .byte $CA
        .byte $C6
        .byte $C8
        .byte $FA
        .byte $C6

BGColors
        .byte $84
        .byte $94
        .byte $8A
        .byte $7C
        .byte $8A
        .byte $88
        .byte $C8
        .byte $C6
        .byte $CC
        .byte $B6
        .byte $B4
        .byte $CC
        .byte $66
        .byte $B6
        .byte $B8
        .byte $56
        .byte $6C
        .byte $64
        .byte $56
        .byte $58
        .byte $94
        .byte $88
        .byte $9C
        .byte $84
        .byte $84
        .byte $7C
        .byte $88
        .byte $C4
        .byte $C6
        .byte $CC
        .byte $C6
        .byte $BC
        .byte $BA
        .byte $B6
        .byte $BC
        .byte $6A
        .byte $66
        .byte $6C
        .byte $56
        .byte $94
        .byte $5A
        .byte $9A
        .byte $8A
        .byte $96
        .byte $96
        .byte $8C
        .byte $78
        .byte $78

        org $FFFC
        .word Start
        .word Start
